import React,{useEffect,useState}from'react';
import{Activity,Brain,CalendarDays,ChartNoAxesCombined,Database,FileDown,Flame,Gauge,Globe2,History,KeyRound,Layers3,MessageSquare,Newspaper,RefreshCw,ScanSearch,ShieldAlert,Target,Zap}from'lucide-react';
import TradingViewChart from'./TradingViewChart';
import EconomicCalendar from'./EconomicCalendar';
import NewsPanel from'./NewsPanel';
import ReportButton from'./ReportButton';

const API=import.meta.env.VITE_API_URL||'';
const symbols=['XAUUSD','EURUSD','GBPUSD','USDJPY','BTCUSD','NAS100','US30'];
const timeframes=['1m','5m','15m','1h','4h','1D'];
const tfMap={'1m':'1','5m':'5','15m':'15','1h':'60','4h':'240','1D':'D'};
const zero={valid:false,bias:'—',action:'CONNECT DATA',score:50,probability_up:50,probability_down:50,confidence:0,trade_readiness:0,buyer_aggression:50,seller_aggression:50,components:{},math:{},volume_profile:{},news:{articles:[]},cot:{}};
const fmt=(v,d=3)=>v==null||Number.isNaN(Number(v))?'—':Number(v).toFixed(d);
const loadCreds=()=>{try{return JSON.parse(localStorage.getItem('night_quant_creds')||'{}')}catch{return{}}};

function Pill({children,tone=''}){return <span className={`pill ${tone}`}>{children}</span>}
function Card({title,icon:Icon,children,className=''}){return <section className={`card ${className}`}><h3>{Icon&&<Icon size={15}/>} {title}</h3>{children}</section>}
function Meter({name,value,centered=false}){const v=Number(value||0),w=centered?Math.min(100,Math.abs(v)*100):Math.max(0,Math.min(100,v));return <div className="meter"><div><span>{name}</span><b>{centered?(v>=0?'+':'')+v.toFixed(3):Math.round(v)+'%'}</b></div><i><em style={{width:`${w}%`}}/></i></div>}
function KV({k,v}){return <div className="kv"><span>{k}</span><b>{v}</b></div>}

export default function App(){
 const[symbol,setSymbol]=useState('XAUUSD'),[tf,setTf]=useState('5m'),[data,setData]=useState(zero),[mtf,setMtf]=useState(null),[loading,setLoading]=useState(false),[tab,setTab]=useState('terminal'),[error,setError]=useState('');
 const[creds,setCreds]=useState(loadCreds),[showKeys,setShowKeys]=useState(false),[chat,setChat]=useState([{role:'bot',text:'NIGHT Quant Chat ready. Ask about bias, news, COT, macro, volume, formula, entry, SL or TP.'}]),[msg,setMsg]=useState('');
 const components=data.components||{},math=data.math||{},vp=data.volume_profile||{},news=data.news||{articles:[]},cot=data.cot||{};
 async function post(path,body){const r=await fetch(`${API}${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.detail||`API ${r.status}`);return j}
 async function run(){setLoading(true);setError('');try{const body={symbol,timeframe:tf,credentials:creds};const [single,multi]=await Promise.all([post('/api/analyse',body),post('/api/analyse-mtf',body)]);setData(single);setMtf(multi)}catch(e){setError(e.message||'Analysis failed')}finally{setLoading(false)}}
 function saveCreds(){localStorage.setItem('night_quant_creds',JSON.stringify(creds));setShowKeys(false);run()}
 async function sendChat(){const q=msg.trim();if(!q)return;setChat(x=>[...x,{role:'me',text:q}]);setMsg('');try{const j=await post('/api/chat',{message:q,analysis:data});setChat(x=>[...x,{role:'bot',text:j.answer||'No answer'}])}catch{setChat(x=>[...x,{role:'bot',text:'Chat API error.'}])}}
 useEffect(()=>{run()},[]);
 const tone=data.action==='LONG'?'good':data.action==='SHORT'?'bad':data.action==='WAIT'?'warn':'';
 const latestCot=cot.latest||{};
 const institutional=data.institutional_factors||{};
 return <div className="app">
  <aside><div className="logo"><Brain/><b>NIGHT</b><small>INSTITUTION</small></div>{[
   ['terminal',ChartNoAxesCombined,'Command'],['quant',Gauge,'Quant Lab'],['news',Newspaper,'News Intel'],['chat',MessageSquare,'Quant Chat'],['scanner',ScanSearch,'Scanner'],['macro',Globe2,'Macro'],['cot',Activity,'COT'],['calendar',CalendarDays,'Calendar'],['journal',History,'Journal'],['data',Database,'Data Center']
  ].map(([id,I,l])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><I size={16}/><span>{l}</span></button>)}</aside>
  <main>
   <header><div><small>INSTITUTIONAL QUANT MARKET INTELLIGENCE</small><h1>{symbol} <Pill tone={data.valid?'live':'warn'}>{data.valid?'MODEL LIVE':'DATA REQUIRED'}</Pill></h1></div><div className="headeractions"><ReportButton symbol={symbol} timeframe={tf} data={data} mtf={mtf} news={news}/><button className="ghost" onClick={()=>setShowKeys(v=>!v)}><KeyRound size={14}/> Data Keys</button><div className="status"><span/>ENGINE ONLINE</div></div></header>
   <div className="toolbar"><select value={symbol} onChange={e=>setSymbol(e.target.value)}>{symbols.map(x=><option key={x}>{x}</option>)}</select><select value={tf} onChange={e=>setTf(e.target.value)}>{timeframes.map(x=><option key={x}>{x}</option>)}</select><button onClick={run} disabled={loading}><Zap size={16}/>{loading?'CALCULATING…':'RUN INSTITUTIONAL ANALYSIS'}</button></div>
   {showKeys&&<div className="keys"><b>DATA ENRICHMENT</b><p>XAU core volume can use COMEX Gold futures proxy without OANDA. Twelve Data is optional fallback. FRED adds official macro. BTCUSD uses Binance public exchange volume.</p><input placeholder="Twelve Data API key (optional)" value={creds.twelve_key||''} onChange={e=>setCreds({...creds,twelve_key:e.target.value})}/><input placeholder="FRED API key" value={creds.fred_key||''} onChange={e=>setCreds({...creds,fred_key:e.target.value})}/><input type="password" placeholder="OANDA practice token (optional)" value={creds.oanda_token||''} onChange={e=>setCreds({...creds,oanda_token:e.target.value})}/><button onClick={saveCreds}>SAVE LOCALLY + RECALCULATE</button><small>Secrets stay in browser localStorage and are sent only to your deployment API.</small></div>}
   {error&&<div className="error">{error}</div>}
   {!data.valid&&<div className="setupbanner"><b>Quant market bars unavailable.</b><span>Engine refuses to fabricate numbers. XAU should attempt COMEX GC proxy; BTC uses Binance. Provider errors: {(data.provider_errors||[]).join(' · ')||'none reported'}.</span></div>}

   {tab==='terminal'&&<>
    <div className="hero"><div><small>FINAL QUANT BIAS</small><strong>{data.bias}</strong><span>Edge {fmt(data.edge,4)}</span></div><div><small>EXECUTION</small><strong className={tone}>{data.action}</strong><span>Readiness {fmt(data.trade_readiness,1)}%</span></div><div><small>DIRECTION PROBABILITY</small><strong>{fmt(data.probability_up,1)}%</strong><span>Up vs {fmt(data.probability_down,1)}% down</span></div><div><small>EXPECTED VALUE</small><strong>{data.bias==='BEARISH'?fmt(data.ev_short_r):fmt(data.ev_long_r)}R</strong><span>Canonical 1.5R model</span></div></div>
    <div className="workspace"><div className="chartcol"><Card title="TradingView Market Chart" icon={ChartNoAxesCombined} className="chartcard"><TradingViewChart symbol={symbol} interval={tfMap[tf]}/></Card><div className="row3">
      <Card title="Volume Profile" icon={Layers3}><KV k="VAH" v={fmt(vp.vah)}/><KV k="POC" v={fmt(vp.poc)}/><KV k="VAL" v={fmt(vp.val)}/><p>Source <b>{data.source||'—'}</b><br/>{data.volume_type||'—'}</p></Card>
      <Card title="Aggression / Flow" icon={Flame}><Meter name="Buyer aggression" value={data.buyer_aggression}/><Meter name="Seller aggression" value={data.seller_aggression}/><KV k="Signed pressure" v={fmt(math.signed_volume_pressure)}/><KV k="Volume z" v={fmt(math.volume_z,2)}/></Card>
      <Card title="Risk / Probability" icon={Target}><Meter name="P(up)" value={data.probability_up}/><Meter name="P(down)" value={data.probability_down}/><KV k="EV long" v={`${fmt(data.ev_long_r)}R`}/><KV k="EV short" v={`${fmt(data.ev_short_r)}R`}/><KV k="Event risk" v={`${fmt(data.event_risk,1)}%`}/></Card>
     </div></div>
     <div className="sidecol"><Card title="Model State" icon={Activity}><KV k="Regime" v={data.regime||'—'}/><KV k="Confidence" v={`${fmt(data.confidence,1)}%`}/><KV k="Conflict" v={`${fmt(data.conflict,1)}%`}/><KV k="Data quality" v={`${fmt(data.data_quality,1)}%`}/></Card><Card title="Exact Multi-Timeframe" icon={RefreshCw}>{timeframes.map(x=>{const r=mtf?.timeframes?.[x]||{};return <div className="mtf" key={x}><b>{x}</b><span>{r.valid?fmt(r.probability_up,1)+'%':'—'}</span><Pill tone={r.action==='LONG'?'good':r.action==='SHORT'?'bad':'warn'}>{r.action||'NO DATA'}</Pill></div>})}{mtf?.valid&&<p>Consensus <b>{mtf.action}</b> · P(up) <b>{fmt(mtf.probability_up,1)}%</b> · agreement <b>{fmt(mtf.agreement,1)}%</b></p>}</Card><Card title="Institutional Inputs" icon={Database}>{Object.entries(institutional).map(([k,v])=><KV key={k} k={k.replaceAll('_',' ')} v={(Number(v)>=0?'+':'')+fmt(v,3)}/>)}</Card></div></div>
    <div className="row4"><Card title="Quant Thesis" icon={Brain}><p>{data.scenario||data.reason||'No thesis.'}</p><b>Invalidation</b><p>{data.invalidation||'—'}</p></Card><Card title="Trend Math" icon={Gauge}><KV k="Momentum z" v={fmt(math.momentum_z)}/><KV k="Trend t-stat" v={fmt(math.trend_t_stat)}/><KV k="R²" v={fmt(math.trend_r2)}/><KV k="Kaufman ER" v={fmt(math.efficiency_ratio)}/></Card><Card title="Positioning" icon={Activity}><KV k="COT score" v={fmt(cot.score)}/><KV k="COT z" v={fmt(cot.zscore)}/><KV k="Managed Money net" v={fmt(latestCot.managed_money_net,0)}/><KV k="Net / OI" v={fmt((latestCot.net_pct_oi||0)*100,2)+'%'}/></Card><Card title="News Intelligence" icon={Newspaper}><KV k="News score" v={fmt(news.score)}/><KV k="Headlines" v={news.count??0}/><KV k="Source" v={news.source||'GDELT'}/><p>{news.articles?.[0]?.title||'No headline.'}</p></Card></div>
   </>}

   {tab==='quant'&&<><Card title="Quant Formula Engine" icon={Gauge}><div className="formula">{data.formula||'Model: standardized momentum + OLS trend significance + efficiency ratio + volume pressure + volume profile + structure + macro/news/COT blend → latent edge → logistic directional probability → expected R.'}</div></Card><div className="row3"><Card title="Raw Statistics" icon={Activity}>{Object.entries(math).map(([k,v])=><KV key={k} k={k.replaceAll('_',' ')} v={fmt(v,5)}/>)}</Card><Card title="Weighted Components" icon={Layers3}>{Object.entries(components).map(([k,v])=><Meter key={k} name={k} value={v} centered/>)}</Card><Card title="Model Outputs" icon={Target}><KV k="Edge" v={fmt(data.edge,4)}/><KV k="P up" v={fmt(data.probability_up,2)+'%'}/><KV k="P down" v={fmt(data.probability_down,2)+'%'}/><KV k="EV long" v={fmt(data.ev_long_r)+'R'}/><KV k="EV short" v={fmt(data.ev_short_r)+'R'}/><KV k="Readiness" v={fmt(data.trade_readiness,1)+'%'}/></Card></div></>}

   {tab==='news'&&<div className="row2"><Card title="Near-Real-Time News Intelligence" icon={Newspaper}><NewsPanel news={news}/></Card><Card title="News Quantization" icon={Gauge}><KV k="Headline score" v={fmt(news.score)}/><KV k="Event risk" v={fmt(data.event_risk,1)+'%'}/><KV k="News articles" v={news.count??0}/><p>Headlines are retrieved through GDELT DOC 2.0 and transformed with a transparent finance-specific headline lexicon. This is a fast signal, not a substitute for full-text NLP validation.</p></Card></div>}

   {tab==='chat'&&<Card title="Quant Chat" icon={MessageSquare} className="chatcard"><div className="chatlog">{chat.map((x,i)=><div key={i} className={`bubble ${x.role}`}>{x.text}</div>)}</div><div className="chatinput"><input value={msg} onChange={e=>setMsg(e.target.value)} onKeyDown={e=>e.key==='Enter'&&sendChat()} placeholder="Ask: news impact? COT? why long? volume? macro? entry/SL/TP?"/><button onClick={sendChat}>SEND</button></div></Card>}

   {tab==='scanner'&&<Card title="Institutional Opportunity Scanner" icon={ScanSearch}><p>Scanner ranks only calculated real-data markets; it does not synthesize fake scores.</p><table><thead><tr><th>Market</th><th>Primary free source</th><th>Current model</th></tr></thead><tbody>{symbols.map(s=><tr key={s}><td>{s}</td><td>{s==='XAUUSD'?'COMEX GC proxy':s==='BTCUSD'?'Binance public':'Twelve Data / OANDA optional'}</td><td>{s===symbol&&data.valid?`${data.action} · ${fmt(data.probability_up,1)}% up · ${fmt(data.trade_readiness,1)}% ready`:'Run model'}</td></tr>)}</tbody></table></Card>}

   {tab==='macro'&&<div className="row3"><Card title="FRED Macro" icon={Globe2}><p>{data.macro_source||'Add FRED key for official macro enrichment.'}</p>{Object.entries(data.macro_details||{}).map(([k,v])=><KV key={k} k={k} v={fmt(v)}/>)}</Card><Card title="Institutional Blend" icon={Activity}>{Object.entries(institutional).map(([k,v])=><Meter key={k} name={k} value={v} centered/>)}</Card><Card title="Method" icon={Brain}><p>Gold macro blends standardized real-yield, nominal-yield, front-end yield, unemployment and CPI momentum with GDELT news and CFTC managed-money positioning before entering the quant edge.</p></Card></div>}

   {tab==='cot'&&<div className="row2"><Card title="CFTC Managed Money Gold" icon={Activity}><KV k="Source" v={cot.source||'CFTC PRE'}/><KV k="Positioning score" v={fmt(cot.score)}/><KV k="52-week z-score" v={fmt(cot.zscore)}/><KV k="Report date" v={latestCot.date||'—'}/><KV k="Long" v={fmt(latestCot.managed_money_long,0)}/><KV k="Short" v={fmt(latestCot.managed_money_short,0)}/><KV k="Net" v={fmt(latestCot.managed_money_net,0)}/><KV k="Open interest" v={fmt(latestCot.open_interest,0)}/></Card><Card title="Interpretation" icon={Brain}><p>Managed-money net exposure is normalized by open interest, then standardized against recent history. The z-score is squashed to [-1,+1] before entering XAU's macro blend.</p></Card></div>}

   {tab==='calendar'&&<Card title="Live Economic Calendar" icon={CalendarDays}><EconomicCalendar/></Card>}
   {tab==='journal'&&<div className="row3"><Card title="Journal" icon={History}><p>Trade-outcome persistence is the next calibration layer: setup, entry, exit, MAE, MFE, R, model probability and news/COT snapshot.</p></Card><Card title="Calibration" icon={Activity}><p>Brier score, probability bucket accuracy, walk-forward hit rate, EV by regime and Monte Carlo bootstrap are planned for model validation.</p></Card><Card title="Decision Quality" icon={ShieldAlert}><p>Wins and losses will be separated from decision quality, allowing lucky wins and good losses to be tagged correctly.</p></Card></div>}
   {tab==='data'&&<Card title="Institutional Data Center" icon={Database}><table><thead><tr><th>Layer</th><th>Source</th><th>Frequency / type</th></tr></thead><tbody><tr><td>Gold price + volume proxy</td><td>COMEX GC futures via free delayed feed</td><td>Intraday OHLCV / exchange volume</td></tr><tr><td>Crypto</td><td>Binance public</td><td>Exchange OHLCV</td></tr><tr><td>FX fallback</td><td>Twelve Data / OANDA optional</td><td>REST / tick-volume dependent</td></tr><tr><td>Macro</td><td>FRED official</td><td>Official releases / daily-monthly</td></tr><tr><td>News</td><td>GDELT DOC 2.0</td><td>Near-real-time global headlines</td></tr><tr><td>Positioning</td><td>CFTC PRE</td><td>Weekly COT</td></tr><tr><td>Chart</td><td>TradingView</td><td>Interactive market chart</td></tr><tr><td>Calendar</td><td>TradingView widget</td><td>Economic events</td></tr></tbody></table></Card>}
   <footer>NIGHT Institutional Quant is decision-support research. Models estimate probabilities and expected value; they do not guarantee outcomes.</footer>
  </main>
 </div>
}
