import React,{useEffect,useState}from'react';
import{Activity,Brain,CalendarDays,ChartNoAxesCombined,Database,Flame,Gauge,Globe2,History,KeyRound,Layers3,MessageSquare,Newspaper,RefreshCw,ShieldAlert,Ship,Target,TrendingUp,Zap}from'lucide-react';
import TradingViewChart from'./TradingViewChart';
import EconomicCalendar from'./EconomicCalendar';
import NewsPanel from'./NewsPanel';
import ReportButton from'./ReportButton';
import EngineSelector from'./EngineSelector';

const API=import.meta.env.VITE_API_URL||'';
const symbols=['XAUUSD','EURUSD','GBPUSD','USDJPY','BTCUSD','NAS100','US30'];
const timeframes=['1m','5m','15m','1h','4h','1D'];
const tfMap={'1m':'1','5m':'5','15m':'15','1h':'60','4h':'240','1D':'D'};
const zero={valid:false,bias:'—',action:'CONNECT DATA',score:50,probability_up:50,probability_down:50,confidence:0,trade_readiness:0,buyer_aggression:50,seller_aggression:50,components:{},math:{},volume_profile:{},news:{articles:[]},cot:{},activity:{oil:{},shipping:{vessels:[]}}};
const fmt=(v,d=3)=>v==null||Number.isNaN(Number(v))?'—':Number(v).toFixed(d);
const loadCreds=()=>{try{return JSON.parse(localStorage.getItem('night_quant_creds')||'{}')}catch{return{}}};
function Pill({children,tone=''}){return <span className={`pill ${tone}`}>{children}</span>}
function Card({title,icon:Icon,children,className=''}){return <section className={`card ${className}`}><h3>{Icon&&<Icon size={15}/>} {title}</h3>{children}</section>}
function Meter({name,value,centered=false}){const v=Number(value||0),w=centered?Math.min(100,Math.abs(v)*100):Math.max(0,Math.min(100,v));return <div className="meter"><div><span>{name}</span><b>{centered?(v>=0?'+':'')+v.toFixed(3):Math.round(v)+'%'}</b></div><i><em style={{width:`${w}%`}}/></i></div>}
function KV({k,v}){return <div className="kv"><span>{k}</span><b>{v}</b></div>}

export default function App(){
 const[symbol,setSymbol]=useState('XAUUSD'),[tf,setTf]=useState('5m'),[engine,setEngine]=useState('master'),[data,setData]=useState(zero),[mtf,setMtf]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const[creds,setCreds]=useState(loadCreds),[showKeys,setShowKeys]=useState(false),[chat,setChat]=useState([{role:'bot',text:'NIGHT AI ready. Ask about current bias, setup quality, news, oil, shipping, positioning, entry, stop or targets.'}]),[msg,setMsg]=useState('');
 const components=data.components||{},math=data.math||{},vp=data.volume_profile||{},news=data.news||{articles:[]},cot=data.cot||{},activity=data.activity||{oil:{},shipping:{vessels:[]}},latestCot=cot.latest||{},institutional=data.institutional_factors||{};
 async function post(path,body){const r=await fetch(`${API}${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.detail||`API ${r.status}`);return j}
 async function get(path){const r=await fetch(`${API}${path}`);const j=await r.json();if(!r.ok)throw new Error(j.detail||`API ${r.status}`);return j}
 async function run(){setLoading(true);setError('');try{const body={symbol,timeframe:tf,credentials:creds};const[single,multi]=await Promise.all([post('/api/analyse',body),post('/api/analyse-mtf',body)]);setData(single);setMtf(multi)}catch(e){setError(e.message||'Analysis failed')}finally{setLoading(false)}}
 async function refreshLive(){try{const[n,a]=await Promise.all([get(`/api/news/${symbol}`),get('/api/activity')]);setData(x=>({...x,news:n,activity:a}))}catch{}}
 function saveCreds(){localStorage.setItem('night_quant_creds',JSON.stringify(creds));setShowKeys(false);run()}
 async function sendChat(){const q=msg.trim();if(!q)return;setChat(x=>[...x,{role:'me',text:q}]);setMsg('');try{const j=await post('/api/chat',{message:q,analysis:data});setChat(x=>[...x,{role:'bot',text:j.answer||'No answer'}])}catch{setChat(x=>[...x,{role:'bot',text:'Chat API error.'}])}}
 useEffect(()=>{run();const t=setInterval(refreshLive,30000);return()=>clearInterval(t)},[symbol]);
 const tone=data.action==='LONG'?'good':data.action==='SHORT'?'bad':'warn';
 const atr=data.last_price&&math.atr_pct?data.last_price*math.atr_pct:null;
 const stop=data.bias==='BULLISH'&&atr?data.last_price-1.2*atr:data.bias==='BEARISH'&&atr?data.last_price+1.2*atr:null;
 const tp1=data.bias==='BULLISH'&&atr?data.last_price+1.5*atr:data.bias==='BEARISH'&&atr?data.last_price-1.5*atr:null;
 const tp2=data.bias==='BULLISH'&&atr?data.last_price+2.4*atr:data.bias==='BEARISH'&&atr?data.last_price-2.4*atr:null;
 const oil=activity.oil||{},shipping=activity.shipping||{};

 const master=<><div className="hero"><div><small>FINAL QUANT BIAS</small><strong>{data.bias}</strong><span>Model score {fmt(data.score,1)}/100</span></div><div><small>EXECUTION</small><strong className={tone}>{data.action}</strong><span>Readiness {fmt(data.trade_readiness,1)}%</span></div><div><small>DIRECTION PROBABILITY</small><strong>{fmt(data.probability_up,1)}%</strong><span>Up vs {fmt(data.probability_down,1)}% down</span></div><div><small>EXPECTED VALUE</small><strong>{data.bias==='BEARISH'?fmt(data.ev_short_r):fmt(data.ev_long_r)}R</strong><span>Current model expectancy</span></div></div>
 <div className="activityStrip">{Object.entries(oil).map(([k,v])=><span key={k}><b>{k}</b> {v?.price==null?'—':Number(v.price).toFixed(2)} {v?.currency||''}</span>)}<span><b>AIS</b> {shipping.count??0} vessels</span><span><b>NEWS</b> {news.count??0} headlines</span><span><b>EVENT RISK</b> {fmt(data.event_risk,0)}%</span></div>
 <div className="workspace"><div className="chartcol"><Card title="TradingView Market Chart" icon={ChartNoAxesCombined} className="chartcard"><TradingViewChart symbol={symbol} interval={tfMap[tf]}/></Card><div className="row3"><Card title="Volume Profile" icon={Layers3}><KV k="VAH" v={fmt(vp.vah)}/><KV k="POC" v={fmt(vp.poc)}/><KV k="VAL" v={fmt(vp.val)}/><p>Source <b>{data.source||'—'}</b><br/>{data.volume_type||'—'}</p></Card><Card title="Aggression / Flow" icon={Flame}><Meter name="Buyer aggression" value={data.buyer_aggression}/><Meter name="Seller aggression" value={data.seller_aggression}/><KV k="Flow state" v={data.buyer_aggression>60?'BUYER DOMINANT':data.seller_aggression>60?'SELLER DOMINANT':'BALANCED'}/><KV k="Volume condition" v={Number(math.volume_z||0)>1?'EXPANDED':Number(math.volume_z||0)<-1?'THIN':'NORMAL'}/></Card><Card title="Institutional Inputs" icon={Database}>{Object.entries(institutional).map(([k,v])=><KV key={k} k={k.replaceAll('_',' ')} v={(Number(v)>=0?'+':'')+fmt(v,3)}/>)}</Card></div></div><div className="sidecol"><Card title="Model State" icon={Activity}><KV k="Regime" v={data.regime||'—'}/><KV k="Confidence" v={`${fmt(data.confidence,1)}%`}/><KV k="Conflict" v={`${fmt(data.conflict,1)}%`}/><KV k="Data quality" v={`${fmt(data.data_quality,1)}%`}/></Card><Card title="Exact Multi-Timeframe" icon={RefreshCw}>{timeframes.map(x=>{const r=mtf?.timeframes?.[x]||{};return <div className="mtf" key={x}><b>{x}</b><span>{r.valid?fmt(r.probability_up,1)+'%':'—'}</span><Pill tone={r.action==='LONG'?'good':r.action==='SHORT'?'bad':'warn'}>{r.action||'NO DATA'}</Pill></div>})}{mtf?.valid&&<p>Consensus <b>{mtf.action}</b> · P(up) <b>{fmt(mtf.probability_up,1)}%</b> · agreement <b>{fmt(mtf.agreement,1)}%</b></p>}</Card><Card title="Positioning / News" icon={Brain}><KV k="COT state" v={Number(cot.score||0)>0.25?'BULLISH POSITIONING':Number(cot.score||0)<-0.25?'BEARISH POSITIONING':'NEUTRAL'}/><KV k="Managed money net" v={fmt(latestCot.managed_money_net,0)}/><KV k="News impact" v={Number(news.score||0)>0.25?'POSITIVE':Number(news.score||0)<-0.25?'NEGATIVE':'MIXED'}/><KV k="Headline count" v={news.count??0}/></Card></div></div></>;

 const execution=<div className="row3"><Card title="Execution Engine" icon={Target}><KV k="Action" v={data.action}/><KV k="Bias" v={data.bias}/><KV k="Readiness" v={fmt(data.trade_readiness,1)+'%'}/><KV k="Confidence" v={fmt(data.confidence,1)+'%'}/></Card><Card title="Trade Levels" icon={Target}><KV k="Reference price" v={fmt(data.last_price,5)}/><KV k="Invalidation" v={fmt(stop,5)}/><KV k="Target 1" v={fmt(tp1,5)}/><KV k="Target 2" v={fmt(tp2,5)}/></Card><Card title="Execution Constraints" icon={ShieldAlert}><KV k="Event risk" v={fmt(data.event_risk,1)+'%'}/><KV k="Volatility" v={fmt(data.volatility,1)+'%'}/><KV k="Conflict" v={fmt(data.conflict,1)+'%'}/><KV k="Data quality" v={fmt(data.data_quality,1)+'%'}/></Card></div>;
 const volume=<div className="row3"><Card title="Volume Profile" icon={Layers3}><KV k="VAH" v={fmt(vp.vah)}/><KV k="POC" v={fmt(vp.poc)}/><KV k="VAL" v={fmt(vp.val)}/></Card><Card title="Flow Pressure" icon={Flame}><Meter name="Buyer aggression" value={data.buyer_aggression}/><Meter name="Seller aggression" value={data.seller_aggression}/><KV k="Flow" v={data.buyer_aggression>60?'BUYER DOMINANT':data.seller_aggression>60?'SELLER DOMINANT':'BALANCED'}/></Card><Card title="Data Provenance" icon={Database}><KV k="Source" v={data.source||'NO DATA'}/><KV k="Volume type" v={data.volume_type||'NO DATA'}/><KV k="Quality" v={fmt(data.data_quality,1)+'%'}/></Card></div>;
 const statistics=<div className="row3"><Card title="Quant Result" icon={Gauge}><KV k="Model score" v={fmt(data.score,1)+'/100'}/><KV k="Bias" v={data.bias}/><KV k="Regime" v={data.regime||'—'}/><KV k="Confidence" v={fmt(data.confidence,1)+'%'}/></Card><Card title="Probability" icon={Target}><KV k="Upside" v={fmt(data.probability_up,2)+'%'}/><KV k="Downside" v={fmt(data.probability_down,2)+'%'}/><KV k="EV long" v={fmt(data.ev_long_r)+'R'}/><KV k="EV short" v={fmt(data.ev_short_r)+'R'}/></Card><Card title="Internal Model" icon={ShieldAlert}><p>The mathematical model is active internally. NIGHT exposes the decision outputs, confidence, risk state and market interpretation—not the underlying formula implementation.</p></Card></div>;
 const intermarket=<div className="row3"><Card title="Intermarket Engine" icon={Globe2}><KV k="Intermarket state" v={Number(components.intermarket||0)>0.2?'SUPPORTIVE':Number(components.intermarket||0)<-0.2?'HEADWIND':'MIXED'}/><KV k="Macro state" v={Number(components.macro||0)>0.2?'SUPPORTIVE':Number(components.macro||0)<-0.2?'HEADWIND':'MIXED'}/></Card><Card title="Energy Board" icon={TrendingUp}>{Object.entries(oil).map(([k,v])=><KV key={k} k={k} v={v?.price==null?'NO DATA':`${Number(v.price).toFixed(2)} ${v.currency||''}`}/>)}</Card><Card title="CFTC Positioning" icon={Database}><KV k="Positioning" v={Number(cot.score||0)>0.25?'BULLISH':Number(cot.score||0)<-0.25?'BEARISH':'NEUTRAL'}/><KV k="Managed money net" v={fmt(latestCot.managed_money_net,0)}/></Card></div>;
 const newsView=<div className="row2"><Card title="24/7 Live News Activity" icon={Newspaper}><NewsPanel news={news}/></Card><Card title="Live News State" icon={Gauge}><KV k="Impact" v={Number(news.score||0)>0.25?'POSITIVE':Number(news.score||0)<-0.25?'NEGATIVE':'MIXED'}/><KV k="Event risk" v={fmt(data.event_risk,1)+'%'}/><KV k="Headlines" v={news.count??0}/><KV k="Source" v={news.source||'GDELT'}/><p>Auto-refresh every 30 seconds while the terminal is open.</p></Card></div>;
 const events=<Card title="Live Economic Event Engine" icon={CalendarDays}><EconomicCalendar/></Card>;
 const risk=<div className="row3"><Card title="Expected Value" icon={ShieldAlert}><KV k="EV long" v={fmt(data.ev_long_r)+'R'}/><KV k="EV short" v={fmt(data.ev_short_r)+'R'}/><KV k="P up" v={fmt(data.probability_up,1)+'%'}/><KV k="P down" v={fmt(data.probability_down,1)+'%'}/></Card><Card title="Risk State" icon={Gauge}><KV k="Readiness" v={fmt(data.trade_readiness,1)+'%'}/><KV k="Volatility" v={fmt(data.volatility,1)+'%'}/><KV k="Event risk" v={fmt(data.event_risk,1)+'%'}/><KV k="Data quality" v={fmt(data.data_quality,1)+'%'}/></Card><Card title="Decision Guard" icon={ShieldAlert}><p>{data.action==='WAIT'?'Edge exists but execution conditions are not strong enough yet.':'Current setup passes the model gate. Manage execution and invalidation rather than treating probability as certainty.'}</p></Card></div>;
 const backtest=<div className="row3"><Card title="Model Validation" icon={History}><p>Calibration, probability-bucket accuracy, walk-forward testing, MFE/MAE and regime expectancy will populate as the terminal accumulates trade outcomes.</p></Card><Card title="Current Diagnostics" icon={Activity}><KV k="Conflict" v={fmt(data.conflict,1)+'%'}/><KV k="Data quality" v={fmt(data.data_quality,1)+'%'}/><KV k="MTF agreement" v={mtf?.valid?fmt(mtf.agreement,1)+'%':'NO DATA'}/></Card><Card title="Integrity" icon={ShieldAlert}><p>No fake Sharpe, win-rate or backtest numbers are shown before there is real stored history.</p></Card></div>;
 const shippingView=<div className="row2"><Card title="Live Shipping / Vessel Activity" icon={Ship}><KV k="Tracked vessels" v={shipping.count??0}/><KV k="Source" v={shipping.source||'Open Waters AIS'}/>{(shipping.vessels||[]).slice(0,20).map((v,i)=><div className="kv" key={`${v.mmsi}-${i}`}><span>{v.name||v.mmsi||'Unknown vessel'}</span><b>{v.speed!=null?`${v.speed} kn`:'—'}</b></div>)}</Card><Card title="Maritime Intelligence" icon={Globe2}><p>Use shipping activity as a contextual supply-chain/geopolitical layer. Current free AIS coverage depends on contributing stations, so vessel counts are not a complete global fleet census.</p></Card></div>;
 const chatView=<Card title="NIGHT AI" icon={MessageSquare} className="chatcard"><div className="chatlog">{chat.map((x,i)=><div key={i} className={`bubble ${x.role}`}>{x.text}</div>)}</div><div className="chatinput"><input value={msg} onChange={e=>setMsg(e.target.value)} onKeyDown={e=>e.key==='Enter'&&sendChat()} placeholder="Ask: why this bias? oil? shipping? news? entry? stop? targets?"/><button onClick={sendChat}>SEND</button></div></Card>;
 const report=<div className="row3"><Card title="Report Engine" icon={Database}><p>Generate an institutional report from the current snapshot on demand.</p><ReportButton symbol={symbol} timeframe={tf} data={data} mtf={mtf} news={news}/></Card><Card title="Report Inputs" icon={Database}><KV k="Symbol" v={symbol}/><KV k="Timeframe" v={tf}/><KV k="Data quality" v={fmt(data.data_quality,1)+'%'}/><KV k="Action" v={data.action}/></Card><Card title="Integrity" icon={ShieldAlert}><p>Unavailable metrics remain explicitly unavailable.</p></Card></div>;
 const views={master,execution,volume,statistics,intermarket,news:newsView,events,risk,backtest,chat:chatView,report};

 return <div className="app"><aside><div className="logo"><Brain/><b>NIGHT</b><small>INSTITUTION</small></div><button className={engine==='master'?'active':''} onClick={()=>setEngine('master')}><ChartNoAxesCombined size={16}/><span>Institutional Quant</span></button><button className={engine==='news'?'active':''} onClick={()=>setEngine('news')}><Newspaper size={16}/><span>Live News</span></button><button className={engine==='intermarket'?'active':''} onClick={()=>setEngine('intermarket')}><TrendingUp size={16}/><span>Oil / Intermarket</span></button><button className={engine==='shipping'?'active':''} onClick={()=>setEngine('shipping')}><Ship size={16}/><span>Shipping</span></button><button className={engine==='chat'?'active':''} onClick={()=>setEngine('chat')}><MessageSquare size={16}/><span>NIGHT AI</span></button><button className={engine==='report'?'active':''} onClick={()=>setEngine('report')}><Database size={16}/><span>Report Engine</span></button><button className={engine==='backtest'?'active':''} onClick={()=>setEngine('backtest')}><History size={16}/><span>Validation</span></button><button className={engine==='events'?'active':''} onClick={()=>setEngine('events')}><CalendarDays size={16}/><span>Events</span></button></aside><main><header><div><small>INSTITUTIONAL QUANT MARKET INTELLIGENCE</small><h1>{symbol} <Pill tone={data.valid?'live':'warn'}>{data.valid?'MODEL LIVE':'DATA REQUIRED'}</Pill></h1></div><div className="headeractions"><button className="ghost" onClick={()=>setShowKeys(v=>!v)}><KeyRound size={14}/> Data Keys</button><div className="status"><span/>LIVE ACTIVITY ON</div></div></header><div className="toolbar"><select value={symbol} onChange={e=>setSymbol(e.target.value)}>{symbols.map(x=><option key={x}>{x}</option>)}</select><select value={tf} onChange={e=>setTf(e.target.value)}>{timeframes.map(x=><option key={x}>{x}</option>)}</select><EngineSelector value={engine==='shipping'?'intermarket':engine} onChange={v=>setEngine(v)}/><button onClick={run} disabled={loading}><Zap size={16}/>{loading?'CALCULATING…':'RUN INSTITUTIONAL ANALYSIS'}</button></div>{showKeys&&<div className="keys"><b>DATA ENRICHMENT</b><p>Gold core uses free COMEX futures proxy where available; Twelve Data and FRED are optional enrichment. BTCUSD uses Binance public exchange data.</p><input placeholder="Twelve Data API key (optional)" value={creds.twelve_key||''} onChange={e=>setCreds({...creds,twelve_key:e.target.value})}/><input placeholder="FRED API key" value={creds.fred_key||''} onChange={e=>setCreds({...creds,fred_key:e.target.value})}/><button onClick={saveCreds}>SAVE LOCALLY + RECALCULATE</button></div>}{error&&<div className="error">{error}</div>}{engine==='shipping'?shippingView:(views[engine]||master)}<footer>NIGHT estimates market states, probabilities and execution quality from available live/near-live data. It does not guarantee outcomes.</footer></main></div>
}
