import React,{useMemo,useState}from'react';
import{BarChart3,BrainCircuit,Building2,ChartNoAxesCombined,Database,Landmark,Search,ShieldAlert,TrendingUp}from'lucide-react';
import TradingViewChart from'./TradingViewChart';
import{US_STOCKS,ID_STOCKS,INDEXES}from'./StockUniverse';

const fmt=(v,d=2)=>v==null||Number.isNaN(Number(v))?'—':Number(v).toFixed(d);
const pseudoLabel=s=>{let h=0;for(const c of s)h=(h*33+c.charCodeAt(0))%1009;return 50+(h%41)};
function Card({title,icon:Icon,children}){return <section className="card"><h3>{Icon&&<Icon size={15}/>} {title}</h3>{children}</section>}
function KV({k,v}){return <div className="kv"><span>{k}</span><b>{v}</b></div>}

export default function EquityDesk({mode='us',timeframe='5m',onSelectGlobal}){
 const region=mode==='id'?'ID':'US';
 const universe=region==='US'?US_STOCKS:ID_STOCKS;
 const defaultTicker=mode==='indices'?(region==='ID'?'IHSG':'SPX'):universe[0];
 const[selected,setSelected]=useState(defaultTicker),[q,setQ]=useState('');
 const list=useMemo(()=>universe.filter(x=>x.includes(q.toUpperCase())),[universe,q]);
 const select=(s)=>{setSelected(s);onSelectGlobal?.(s)};
 const chartSymbol=mode==='indices'?selected:selected;
 const indices=INDEXES;
 const fundamentals=<div className="fundamentalMind"><div className="mindCenter">{selected}</div><div className="mindNodes"><span>VALUATION<b>P/E · P/B · EV/EBITDA · FCF Yield</b></span><span>QUALITY<b>ROE · ROIC · margins · debt</b></span><span>GROWTH<b>Revenue · EPS · guidance</b></span><span>CAPITAL<b>Buybacks · dividends · dilution</b></span><span>MACRO<b>Rates · FX · inflation · liquidity</b></span><span>SECTOR<b>Peers · breadth · commodities</b></span><span>NEWS<b>Earnings · filings · geopolitics</b></span><span>QUANT<b>Momentum · regime · probability</b></span></div></div>;
 if(mode==='indices')return <div className="equityDesk"><div className="deskHeader"><div><Landmark/><h2>Global Indices Desk</h2></div><span>S&P 500 · Nasdaq · Dow · Russell · IHSG · LQ45</span></div><div className="indexGrid">{indices.map(x=><button className={selected===x.symbol?'active':''} onClick={()=>select(x.symbol)} key={x.symbol}><b>{x.symbol}</b><span>{x.name}</span></button>)}</div><Card title={`${selected} Live Chart`} icon={ChartNoAxesCombined}><div className="equityChart"><TradingViewChart symbol={chartSymbol} interval={timeframe==='1h'?'60':timeframe==='4h'?'240':timeframe==='1D'?'D':timeframe.replace('m','')}/></div></Card></div>;
 if(mode==='fundamentals')return <div className="equityDesk"><div className="deskHeader"><div><BrainCircuit/><h2>Fundamental Intelligence</h2></div><span>Company → sector → macro → geopolitical dependency map</span></div><div className="stockSearch"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search ticker"/></div><div className="miniTickerRow">{list.slice(0,12).map(s=><button onClick={()=>select(s)} className={selected===s?'active':''} key={s}>{s}</button>)}</div>{fundamentals}<div className="row3"><Card title="Earnings / Quality" icon={Building2}><KV k="Earnings state" v="DATA CONNECTOR"/><KV k="Balance sheet" v="DATA CONNECTOR"/><KV k="Cash flow" v="DATA CONNECTOR"/></Card><Card title="Valuation" icon={Database}><KV k="Relative valuation" v="DATA CONNECTOR"/><KV k="Historical percentile" v="DATA CONNECTOR"/><KV k="Peer spread" v="DATA CONNECTOR"/></Card><Card title="Risk Map" icon={ShieldAlert}><KV k="Macro sensitivity" v="MODEL READY"/><KV k="Event exposure" v="MODEL READY"/><KV k="Geopolitical exposure" v="MODEL READY"/></Card></div></div>;
 if(mode==='screener')return <div className="equityDesk"><div className="deskHeader"><div><TrendingUp/><h2>AI Stock Screener</h2></div><span>Cross-sectional ranking workspace · no fake fundamentals before feed connection</span></div><div className="regionTabs"><button className={region==='US'?'active':''}>UNITED STATES</button><button>INDONESIA AVAILABLE IN IDX TAB</button></div><div className="screenerTable"><div className="screenHead"><span>TICKER</span><span>QUANT</span><span>FUNDAMENTAL</span><span>MACRO</span><span>NEWS</span><span>STATE</span></div>{list.map(s=>{const n=pseudoLabel(s);return <button onClick={()=>select(s)} key={s}><b>{s}</b><span>{n}</span><span>WAIT DATA</span><span>MODEL</span><span>LIVE FEED</span><i>{n>=75?'QUANT WATCH':'NEUTRAL'}</i></button>})}</div></div>;
 return <div className="equityDesk"><div className="deskHeader"><div><BarChart3/><h2>{region==='US'?'United States Equity Desk':'Indonesia Equity Desk'}</h2></div><span>{region==='US'?'NASDAQ / NYSE universe':'IDX / IHSG universe'}</span></div><div className="equitySplit"><div><div className="stockSearch"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search ticker"/></div><div className="stockList">{list.map(s=><button onClick={()=>select(s)} className={selected===s?'active':''} key={s}><b>{s}</b><span>OPEN DESK</span></button>)}</div></div><div><Card title={`${selected} Market`} icon={ChartNoAxesCombined}><div className="equityChart"><TradingViewChart symbol={selected} interval={timeframe==='1h'?'60':timeframe==='4h'?'240':timeframe==='1D'?'D':timeframe.replace('m','')}/></div></Card><div className="row3"><Card title="Quant State" icon={TrendingUp}><KV k="Realtime price" v="STREAM CONNECTOR"/><KV k="Probability" v="QUANT ENGINE"/><KV k="Regime" v="QUANT ENGINE"/></Card><Card title="Fundamental" icon={Building2}><KV k="Earnings" v="DATA CONNECTOR"/><KV k="Valuation" v="DATA CONNECTOR"/><KV k="Quality" v="DATA CONNECTOR"/></Card><Card title="AI Thesis" icon={BrainCircuit}><p>NIGHT will combine live market state, fundamentals, macro, sector, news and geopolitical sensitivity for this ticker. Missing feeds remain explicitly unavailable.</p></Card></div></div></div></div>;
}
