import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import{Activity,Brain,CalendarDays,ChartNoAxesCombined,Database,Flame,Gauge,Globe2,History,KeyRound,Layers3,MessageSquare,RefreshCw,ScanSearch,ShieldAlert,Target,Zap}from'lucide-react';
import TradingViewChart from'./TradingViewChart';
import EconomicCalendar from'./EconomicCalendar';
import'./style.css';

const API=import.meta.env.VITE_API_URL||'';
const symbols=['XAUUSD','EURUSD','GBPUSD','USDJPY','BTCUSD','NAS100','US30'];
const timeframes=['1m','5m','15m','1h','4h','1D'];
const tfMap={'1m':'1','5m':'5','15m':'15','1h':'60','4h':'240','1D':'D'};
const zero={valid:false,bias:'—',action:'CONNECT DATA',score:50,probability_up:50,probability_down:50,confidence:0,trade_readiness:0,buyer_aggression:50,seller_aggression:50,components:{},math:{},volume_profile:{}};
const fmt=(v,d=3)=>v==null?'—':Number(v).toFixed(d);
const loadCreds=()=>{try{return JSON.parse(localStorage.getItem('night_quant_creds')||'{}')}catch{return{}}};
function Pill({children,tone=''}){return <span className={`pill ${tone}`}>{children}</span>}
function Card({title,icon:Icon,children,className=''}){return <section className={`card ${className}`}><h3>{Icon&&<Icon size={15}/>} {title}</h3>{children}</section>}
function Meter({name,value,centered=false}){const v=Number(value||0),w=centered?Math.min(100,Math.abs(v)*100):Math.max(0,Math.min(100,v));return <div className="meter"><div><span>{name}</span><b>{centered?(v>=0?'+':'')+v.toFixed(3):Math.round(v)+'%'}</b></div><i><em style={{width:`${w}%`}}/></i></div>}

function App(){
 const[symbol,setSymbol]=useState('XAUUSD'),[tf,setTf]=useState('5m'),[data,setData]=useState(zero),[mtf,setMtf]=useState(null),[loading,setLoading]=useState(false),[tab,setTab]=useState('terminal'),[error,setError]=useState('');
 const[creds,setCreds]=useState(loadCreds),[showKeys,setShowKeys]=useState(false),[chat,setChat]=useState([{role:'bot',text:'Quant Chat ready. Ask: why bias, volume, macro, formula, entry, SL, TP.'}]),[msg,setMsg]=useState('');
 const components=data.components||{},math=data.math||{},vp=data.volume_profile||{};
 async function post(path,body){const r=await fetch(`${API}${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.detail||`API ${r.status}`);return j}
 async function run(){setLoading(true);setError('');try{const body={symbol,timeframe:tf,credentials:creds};const [single,multi]=await Promise.all([post('/api/analyse',body),post('/api/analyse-mtf',body)]);setData(single);setMtf(multi)}catch(e){setError(e.message||'Analysis failed')}finally{setLoading(false)}}
 function saveCreds(){localStorage.setItem('night_quant_creds',JSON.stringify(creds));setShowKeys(false);run()}
 async function sendChat(){const q=msg.trim();if(!q)return;setChat(x=>[...x,{role:'me',text:q}]);setMsg('');try{const j=await post('/api/chat',{message:q,analysis:data});setChat(x=>[...x,{role:'bot',text:j.answer||'No answer'}])}catch{setChat(x=>[...x,{role:'bot',text:'Chat API error.'}])}}
 useEffect(()=>{run()},[]);
 const tone=data.action==='LONG'?'good':data.action==='SHORT'?'bad':data.action==='WAIT'?'warn':'';
 return <div className="app">
  <aside><div className="logo"><Brain/><b>NIGHT</b><small>QUANT</small></div>{[['terminal',ChartNoAxesCombined,'Command'],['quant',Gauge,'Quant Lab'],['chat',MessageSquare,'Quant Chat'],['scanner',ScanSearch,'Scanner'],['macro',Globe2,'Macro'],['calendar',CalendarDays,'Calendar'],['journal',History,'Journal'],['data',Database,'Data Center']].map(([id,I,l])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><I size={16}/><span>{l}</span></button>)}</aside>
  <main><header><div><small>PERSONAL QUANT MARKET INTELLIGENCE</small><h1>{symbol} <Pill tone={data.valid?'live':'warn'}>{data.valid?'QUANT LIVE':'DATA REQUIRED'}</Pill></h1></div><div className="headeractions"><button className="ghost" onClick={()=>setShowKeys(v=>!v)}><KeyRound size={14}/> Data Keys</button><div className="status"><span/>ENGINE ONLINE</div></div></header>
  <div className="toolbar"><select value={symbol} onChange={e=>setSymbol(e.target.value)}>{symbols.map(x=><option key={x}>{x}</option>)}</select><select value={tf} onChange={e=>setTf(e.target.value)}>{timeframes.map(x=><option key={x}>{x}</option>)}</select><button onClick={run} disabled={loading}><Zap size={16}/>{loading?'CALCULATING…':'RUN QUANT ANALYSIS'}</button></div>
  {showKeys&&<div className="keys"><b>FREE DATA SETUP</b><p>XAU/FX: OANDA practice gives tick-volume; Twelve Data Basic can supply real-time FX/crypto; BTCUSD uses Binance public data. FRED supplies official macro series.</p><input placeholder="Twelve Data API key" value={creds.twelve_key||''} onChange={e=>setCreds({...creds,twelve_key:e.target.value})}/><input type="password" placeholder="OANDA practice token" value={creds.oanda_token||''} onChange={e=>setCreds({...creds,oanda_token:e.target.value})}/><input placeholder="FRED API key" value={creds.fred_key||''} onChange={e=>setCreds({...creds,fred_key:e.target.value})}/><button onClick={saveCreds}>SAVE LOCALLY + ANALYSE</button><small>Stored only in browser localStorage; never commit secrets to GitHub.</small></div>}
  {error&&<div className="error">{error}</div>}{!data.valid&&<div className="setupbanner"><b>No real OHLCV.</b><span>{symbol==='BTCUSD'?'Re-run; Binance public requires no key.':'Open Data Keys and connect OANDA/Twelve Data. Engine refuses to fabricate market numbers.'}</span>{data.provider_errors?.length>0&&<code>{data.provider_errors.join(' · ')}</code>}</div>}

  {tab==='terminal'&&<><div className="hero"><div><small>QUANT BIAS</small><strong>{data.bias}</strong><span>Edge {fmt(data.edge,4)}</span></div><div><small>EXECUTION</small><strong className={tone}>{data.action}</strong><span>Readiness {fmt(data.trade_readiness,1)}%</span></div><div><small>PROBABILITY</small><strong>{fmt(data.probability_up,1)}%</strong><span>Up vs {fmt(data.probability_down,1)}% down</span></div><div><small>EXPECTED VALUE</small><strong>{data.bias==='BEARISH'?fmt(data.ev_short_r):fmt(data.ev_long_r)}R</strong><span>1.5R payoff model</span></div></div>
   <div className="workspace"><div className="chartcol"><Card title="TradingView Live Chart" icon={ChartNoAxesCombined} className="chartcard"><TradingViewChart symbol={symbol} interval={tfMap[tf]}/></Card><div className="row3"><Card title="Real Volume Profile" icon={Layers3}><div className="vp"><div>VAH <b>{fmt(vp.vah)}</b></div><div className="poc">POC <b>{fmt(vp.poc)}</b></div><div>VAL <b>{fmt(vp.val)}</b></div></div><p>Source: <b>{data.source||'—'}</b><br/>Volume: {data.volume_type||'—'}</p></Card><Card title="Aggression / Flow" icon={Flame}><Meter name="Buyer aggression" value={data.buyer_aggression}/><Meter name="Seller aggression" value={data.seller_aggression}/><div className="kv"><span>Signed pressure</span><b>{fmt(math.signed_volume_pressure)}</b></div><div className="kv"><span>Volume z</span><b>{fmt(math.volume_z,2)}</b></div></Card><Card title="Probability / EV" icon={Target}><Meter name="P(up)" value={data.probability_up}/><Meter name="P(down)" value={data.probability_down}/><div className="kv"><span>EV long</span><b>{fmt(data.ev_long_r)}R</b></div><div className="kv"><span>EV short</span><b>{fmt(data.ev_short_r)}R</b></div></Card></div></div>
    <div className="sidecol"><Card title="Quant State" icon={Activity}><div className="kv"><span>Regime</span><b>{data.regime||'—'}</b></div><div className="kv"><span>Confidence</span><b>{fmt(data.confidence,1)}%</b></div><div className="kv"><span>Conflict</span><b>{fmt(data.conflict,1)}%</b></div><div className="kv"><span>Data quality</span><b>{fmt(data.data_quality,1)}%</b></div></Card><Card title="Exact Multi-Timeframe" icon={RefreshCw}>{timeframes.map(x=>{const r=mtf?.timeframes?.[x]||{};return <div className="mtf" key={x}><b>{x}</b><span>{r.valid?fmt(r.probability_up,1)+'%':'—'}</span><Pill tone={r.action==='LONG'?'good':r.action==='SHORT'?'bad':r.action==='WAIT'?'warn':''}>{r.action||'NO DATA'}</Pill></div>})}{mtf?.valid&&<p>HTF-weighted P(up) <b>{fmt(mtf.probability_up,1)}%</b> · agreement <b>{fmt(mtf.agreement,1)}%</b></p>}</Card><Card title="Factor Edge [-1,+1]" icon={Gauge}>{Object.entries(components).map(([k,v])=><Meter key={k} name={k} value={v} centered/>)}</Card></div></div>
   <div className="row4"><Card title="Quant Thesis" icon={Brain}><p>{data.scenario||data.reason||'Connect data.'}</p><b>Invalidation</b><p>{data.invalidation||'—'}</p></Card><Card title="Trend Math" icon={Gauge}><div className="kv"><span>Momentum z</span><b>{fmt(math.momentum_z)}</b></div><div className="kv"><span>Trend t-stat</span><b>{fmt(math.trend_t_stat)}</b></div><div className="kv"><span>R²</span><b>{fmt(math.trend_r2)}</b></div><div className="kv"><span>Kaufman ER</span><b>{fmt(math.efficiency_ratio)}</b></div></Card><Card title="Volatility Math" icon={ShieldAlert}><div className="kv"><span>Realized vol</span><b>{fmt(math.realized_vol,5)}</b></div><div className="kv"><span>ATR %</span><b>{fmt((math.atr_pct||0)*100,3)}%</b></div><div className="kv"><span>ATR z</span><b>{fmt(math.atr_z)}</b></div></Card><Card title="Macro Provenance" icon={Globe2}><p><b>{data.macro_source||'Neutral/no FRED key'}</b></p>{Object.entries(data.macro_details||{}).map(([k,v])=><div className="kv" key={k}><span>{k}</span><b>{fmt(v)}</b></div>)}</Card></div></>}

  {tab==='quant'&&<><Card title="Quant Formula Engine" icon={Gauge}><div className="formula">{data.formula||'Connect data.'}</div></Card><div className="row3"><Card title="Raw Statistics" icon={Activity}>{Object.entries(math).map(([k,v])=><div className="kv" key={k}><span>{k.replaceAll('_',' ')}</span><b>{fmt(v,5)}</b></div>)}</Card><Card title="Weighted Components" icon={Layers3}>{Object.entries(components).map(([k,v])=><div className="kv" key={k}><span>{k}</span><b>{fmt(v,4)}</b></div>)}</Card><Card title="Outputs" icon={Target}><div className="kv"><span>Edge</span><b>{fmt(data.edge,4)}</b></div><div className="kv"><span>P up</span><b>{fmt(data.probability_up,2)}%</b></div><div className="kv"><span>P down</span><b>{fmt(data.probability_down,2)}%</b></div><div className="kv"><span>EV long</span><b>{fmt(data.ev_long_r)}R</b></div><div className="kv"><span>EV short</span><b>{fmt(data.ev_short_r)}R</b></div></Card></div></>}
  {tab==='chat'&&<Card title="Quant Chat" icon={MessageSquare} className="chatcard"><div className="chatlog">{chat.map((x,i)=><div key={i} className={`bubble ${x.role}`}>{x.text}</div>)}</div><div className="chatinput"><input value={msg} onChange={e=>setMsg(e.target.value)} onKeyDown={e=>e.key==='Enter'&&sendChat()} placeholder="Ask: kenapa bullish? buyer winning? macro? formula? entry SL TP?"/><button onClick={sendChat}>SEND</button></div></Card>}
  {tab==='scanner'&&<Card title="Opportunity Scanner" icon={ScanSearch}><p>Scanner does not fabricate rankings. Run each symbol with a real feed; BTCUSD works keyless, FX/XAU requires provider credentials.</p><table><thead><tr><th>Market</th><th>Free source</th><th>Status</th></tr></thead><tbody>{symbols.map(s=><tr key={s}><td>{s}</td><td>{s==='BTCUSD'?'Binance':'OANDA / Twelve Data'}</td><td>{s===symbol&&data.valid?`${data.action} · P(up) ${fmt(data.probability_up,1)}%`:'Calculate'}</td></tr>)}</tbody></table></Card>}
  {tab==='macro'&&<div className="row3"><Card title="FRED Macro" icon={Globe2}><p>{data.macro_source||'Add FRED key in Data Keys.'}</p>{Object.entries(data.macro_details||{}).map(([k,v])=><div className="kv" key={k}><span>{k}</span><b>{fmt(v)}</b></div>)}</Card><Card title="Macro Factor" icon={Activity}><Meter name="Macro edge" value={components.macro} centered/><Meter name="Intermarket edge" value={components.intermarket} centered/></Card><Card title="Method" icon={Brain}><p>Gold macro impulse weights standardized changes in real 10Y, nominal 10Y, 2Y, unemployment and CPI-YoY trend. FX mappings invert/scale the USD impulse by pair.</p></Card></div>}
  {tab==='calendar'&&<Card title="Live Economic Calendar" icon={CalendarDays}><EconomicCalendar/></Card>}
  {tab==='journal'&&<div className="row3"><Card title="Journal" icon={History}><p>Trade outcome store is not connected yet.</p></Card><Card title="Calibration" icon={Activity}><p>Next model-validation layer: Brier score, hit-rate by probability bucket, EV by regime, MFE/MAE and walk-forward tests.</p></Card><Card title="Mistake Detector" icon={ShieldAlert}><p>Will score decision quality independently from win/loss.</p></Card></div>}
  {tab==='data'&&<Card title="Data Center" icon={Database}><table><thead><tr><th>Asset</th><th>Source</th><th>Volume</th><th>Purpose</th></tr></thead><tbody><tr><td>XAU / FX</td><td>OANDA practice</td><td>Tick-volume</td><td>OHLCV, VP, flow proxy</td></tr><tr><td>FX / crypto</td><td>Twelve Data Basic</td><td>Feed dependent</td><td>Real-time REST bars</td></tr><tr><td>BTCUSD</td><td>Binance public</td><td>True exchange volume</td><td>OHLCV quant</td></tr><tr><td>Macro</td><td>FRED official</td><td>n/a</td><td>Yield/inflation/labor quant</td></tr></tbody></table></Card>}
  <footer>Quant decision-support only. No market number is invented when a provider is missing. Spot FX/CFD has no centralized volume tape; tick-volume and exchange-volume are labeled separately.</footer></main></div>
}
createRoot(document.getElementById('root')).render(<App/>);
