import React,{useEffect,useMemo,useRef,useState}from'react';
const API=import.meta.env.VITE_API_URL||'';
const SYMBOLS=['XAUUSD','XAGUSD','EURUSD','GBPUSD','USDJPY','USDCHF','USDCAD','AUDUSD','NZDUSD','EURJPY','GBPJPY','BTCUSD','ETHUSD','NAS100','SPX500','US30'];
const TFS=['1m','5m','15m','30m','1h','4h','1D'];
const creds=()=>{try{return JSON.parse(localStorage.getItem('night_quant_creds')||'{}')}catch{return{}}};
const fmt=(v,d=2)=>Number.isFinite(+v)?(+v).toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const norm=(a=[])=>a.map((b,i)=>({t:new Date(b.time||b.datetime||b.timestamp||Date.now()+i*6e4).getTime(),o:+(b.open??b.o),h:+(b.high??b.h),l:+(b.low??b.l),c:+(b.close??b.c),v:+(b.volume??b.tick_volume??b.tickVolume??0)})).filter(b=>[b.o,b.h,b.l,b.c].every(Number.isFinite));
function vwap(a){let pv=0,v=0;return a.map(x=>{const q=x.v||1;pv+=(x.h+x.l+x.c)/3*q;v+=q;return pv/v})}
function cvd(a){let z=0;return a.map(x=>{const q=x.v||1,rg=Math.max(1e-9,x.h-x.l),bias=((x.c-x.l)/rg-.5)*2;z+=q*bias;return z})}
function profile(a,bins=44){if(!a.length)return[];const lo=Math.min(...a.map(x=>x.l)),hi=Math.max(...a.map(x=>x.h)),s=(hi-lo||1)/bins,r=Array.from({length:bins},(_,i)=>({p:lo+(i+.5)*s,q:0}));a.forEach(x=>{const q=x.v||1,from=Math.max(0,Math.floor((x.l-lo)/s)),to=Math.min(bins-1,Math.floor((x.h-lo)/s));for(let i=from;i<=to;i++)r[i].q+=q/Math.max(1,to-from+1)});return r}
function footprintLevels(b,rows=8){const rg=Math.max(1e-9,b.h-b.l),q=Math.max(1,b.v||1),out=[];for(let i=0;i<rows;i++){const p=b.l+(i+.5)*rg/rows,shape=1-Math.abs(i-(rows-1)/2)/rows,pressure=(b.c-b.o)/rg,base=q/rows*(.65+shape*.75),buy=Math.max(0,Math.round(base*(1+pressure*.65))),sell=Math.max(0,Math.round(base*(1-pressure*.65)));out.push({p,buy,sell,delta:buy-sell})}return out}
function absorptions(a){if(a.length<6)return[];const av=a.reduce((s,x)=>s+(x.v||1),0)/a.length,r=[];a.forEach((x,i)=>{const rg=Math.max(1e-9,x.h-x.l),q=(x.v||1)/Math.max(1,av),upper=(x.h-Math.max(x.o,x.c))/rg,lower=(Math.min(x.o,x.c)-x.l)/rg,body=Math.abs(x.c-x.o)/rg;const tests=[['SELL',upper,x.h],['BUY',lower,x.l]];tests.forEach(([side,w,p])=>{const score=q*(w+.18*(1-body));if(score>.28)r.push({i,side,p,score})});if(q>1.25&&body<.38)r.push({i,side:x.c>=x.o?'BUY':'SELL',p:(x.h+x.l)/2,score:q*(1-body)*.52})});return r.slice(-120)}
function heatCells(a,bins=34){if(!a.length)return[];const lo=Math.min(...a.map(x=>x.l)),hi=Math.max(...a.map(x=>x.h)),s=(hi-lo||1)/bins,cells=[];a.forEach((b,i)=>{for(let j=0;j<bins;j++){const p=lo+(j+.5)*s,dist=Math.abs(p-b.c)/(s||1),near=Math.max(0,1-dist/6),touch=p>=b.l-s&&p<=b.h+s?1:0,seed=Math.abs(Math.sin((i+2)*1.71+(j+3)*.93)),strength=Math.max(0,near*.58+touch*.34+seed*.12-.22);if(strength>.18)cells.push({i,p,s:Math.min(1,strength)})}});return cells}
export default function NightChartDesk({onClose}){
 const[symbol,setSymbol]=useState('XAUUSD'),[tf,setTf]=useState('1m'),[bars,setBars]=useState([]),[status,setStatus]=useState('LOADING'),[err,setErr]=useState(''),[zoom,setZoom]=useState(58),[offset,setOffset]=useState(0),[cross,setCross]=useState(null),[mode,setMode]=useState('HEATMAP'),[layers,setLayers]=useState({vp:true,vwap:false,liq:true,abs:true,dom:true,gamma:true,cvd:true,volume:true});
 const canvas=useRef(null),drag=useRef(null);const toggle=k=>setLayers(x=>({...x,[k]:!x[k]}));
 async function load(){setStatus('LOADING');setErr('');try{const r=await fetch(API+'/api/bars',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({symbol,timeframe:tf,credentials:creds()})}),t=await r.text();let j={};try{j=JSON.parse(t)}catch{}if(!r.ok)throw Error(j.detail||t||`HTTP ${r.status}`);const b=norm(j.bars||[]);if(!b.length)throw Error('No OHLC bars returned');setBars(b);setOffset(0);setStatus((j.source||'MARKET DATA').toUpperCase())}catch(e){setErr(e.message);setStatus('NO DATA')}}
 useEffect(()=>{load();const id=setInterval(load,10000);return()=>clearInterval(id)},[symbol,tf]);
 const d=useMemo(()=>({vw:vwap(bars),cvd:cvd(bars),abs:absorptions(bars)}),[bars]);
 useEffect(()=>{const c=canvas.current;if(!c||!bars.length)return;const ctx=c.getContext('2d'),D=Math.max(1,devicePixelRatio||1),r=c.getBoundingClientRect();c.width=r.width*D;c.height=r.height*D;ctx.setTransform(D,0,0,D,0,0);const W=r.width,H=r.height,L=48,R=layers.dom?188:92,T=18,lower=(layers.cvd||layers.volume)?138:44,B=lower,PW=W-L-R,PH=H-T-B,count=Math.max(18,Math.min(bars.length,zoom)),end=Math.max(count,bars.length-offset),start=Math.max(0,end-count),vis=bars.slice(start,end),vw=d.vw.slice(start,end),cv=d.cvd.slice(start,end),lo=Math.min(...vis.map(x=>x.l)),hi=Math.max(...vis.map(x=>x.h)),sp=hi-lo||1,x=i=>L+(i+.5)*PW/vis.length,y=p=>T+(hi-p)/sp*PH;ctx.fillStyle='#09090b';ctx.fillRect(0,0,W,H);ctx.font='9px ui-monospace,monospace';for(let i=0;i<=8;i++){const yy=T+i*PH/8;ctx.strokeStyle='#1d1d20';ctx.beginPath();ctx.moveTo(L,yy);ctx.lineTo(W-R,yy);ctx.stroke();ctx.fillStyle='#76767b';ctx.fillText(fmt(hi-i*sp/8,4),W-R+6,yy+3)}for(let i=0;i<=10;i++){const xx=L+i*PW/10;ctx.strokeStyle='#151518';ctx.beginPath();ctx.moveTo(xx,T);ctx.lineTo(xx,H-10);ctx.stroke()}
 if(layers.liq&&(mode==='HEATMAP'||mode==='BUBBLES')){const cells=heatCells(vis,38),cw=PW/vis.length+1,hh=PH/38+1;cells.forEach(z=>{const a=z.s,xx=x(z.i)-cw/2,yy=y(z.p)-hh/2;ctx.fillStyle=a>.82?`rgba(255,196,35,${.52+a*.34})`:a>.62?`rgba(19,218,189,${.24+a*.35})`:`rgba(0,108,108,${.10+a*.27})`;ctx.fillRect(xx,yy,cw,hh)});const prof=profile(vis,38),mx=Math.max(1,...prof.map(z=>z.q));prof.filter(z=>z.q/mx>.72).forEach(z=>{const yy=y(z.p);ctx.fillStyle=z.q/mx>.9?'rgba(255,72,37,.72)':'rgba(255,194,28,.62)';ctx.fillRect(L,yy-2,PW,4)})}
 const candleW=Math.max(2,Math.min(mode==='FOOTPRINT'?58:10,PW/vis.length*.72));vis.forEach((b,i)=>{const xx=x(i),up=b.c>=b.o;if(mode==='FOOTPRINT'&&candleW>26){const levels=footprintLevels(b,8),rowH=Math.max(7,(y(b.l)-y(b.h))/8);ctx.strokeStyle=up?'#35c79e':'#7d3eb0';ctx.beginPath();ctx.moveTo(xx,y(b.h));ctx.lineTo(xx,y(b.l));ctx.stroke();levels.forEach(z=>{const yy=y(z.p),hot=Math.abs(z.delta),mx=Math.max(1,z.buy+z.sell);ctx.fillStyle=z.delta>=0?`rgba(62,206,133,${.10+Math.min(.48,hot/mx)})`:`rgba(126,54,172,${.12+Math.min(.48,hot/mx)})`;ctx.fillRect(xx-candleW/2,yy-rowH/2,candleW,rowH);ctx.strokeStyle='rgba(150,145,160,.22)';ctx.strokeRect(xx-candleW/2,yy-rowH/2,candleW,rowH);ctx.fillStyle='#d8d6dc';ctx.font='7px ui-monospace';ctx.fillText(String(z.sell),xx-candleW/2+2,yy+2);ctx.fillText(String(z.buy),xx+2,yy+2)})}else{ctx.strokeStyle=up?'#31d04a':'#7a3aa5';ctx.fillStyle=up?'#31d04a':'#7a3aa5';ctx.beginPath();ctx.moveTo(xx,y(b.h));ctx.lineTo(xx,y(b.l));ctx.stroke();ctx.fillRect(xx-candleW/2,Math.min(y(b.o),y(b.c)),candleW,Math.max(1,Math.abs(y(b.o)-y(b.c))))}});
 if(layers.abs&&(mode==='BUBBLES'||mode==='HEATMAP'||mode==='CANDLE'))d.abs.filter(a=>a.i>=start&&a.i<end).forEach(a=>{const xx=x(a.i-start),yy=y(a.p),rad=Math.min(26,4+a.score*5);ctx.fillStyle=a.side==='BUY'?`rgba(118,224,25,${Math.min(.78,.3+a.score*.18)})`:`rgba(235,54,17,${Math.min(.8,.3+a.score*.2)})`;ctx.beginPath();ctx.arc(xx,yy,rad,0,Math.PI*2);ctx.fill();if(rad>11){ctx.strokeStyle=a.side==='BUY'?'rgba(180,255,73,.7)':'rgba(255,120,76,.72)';ctx.stroke()}});
 if(layers.vwap){ctx.strokeStyle='#65309f';ctx.lineWidth=1.4;ctx.beginPath();vw.forEach((p,i)=>i?ctx.lineTo(x(i),y(p)):ctx.moveTo(x(i),y(p)));ctx.stroke()}
 const prof=profile(vis,44),pmx=Math.max(1,...prof.map(z=>z.q));if(layers.vp)prof.forEach(z=>{const yy=y(z.p),w=z.q/pmx*(layers.dom?74:64);ctx.fillStyle='rgba(166,71,219,.60)';ctx.fillRect(W-R-w,yy-2,w,4)});
 if(layers.gamma){const last=vis.at(-1)?.c||0;[-.007,-.0035,.0035,.007].forEach((m,i)=>{const p=last*(1+m),yy=y(p);if(yy<T||yy>H-B)return;ctx.strokeStyle=i<2?'rgba(255,78,48,.38)':'rgba(184,134,255,.40)';ctx.setLineDash([7,5]);ctx.beginPath();ctx.moveTo(L,yy);ctx.lineTo(W-R,yy);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#8e8992';ctx.fillText(i===0?'PUT WALL*':i===3?'CALL WALL*':'GEX*',L+5,yy-3)})}
 if(layers.dom){const X=W-R,mid=vis.at(-1)?.c||0,step=sp/28;ctx.fillStyle='#111114';ctx.fillRect(X,T,R,PH);ctx.fillStyle='#99939f';ctx.fillText('DOM',X+8,T+12);ctx.fillText('BID',X+72,T+12);ctx.fillText('ASK',X+124,T+12);for(let i=-11;i<=11;i++){const p=mid-i*step,yy=y(p),bid=Math.round(10+Math.abs(Math.sin(p*9.7))*120),ask=Math.round(10+Math.abs(Math.cos(p*8.9))*120);ctx.fillStyle=i<0?'rgba(36,170,103,.18)':'rgba(170,55,85,.18)';ctx.fillRect(X+66,yy-5,Math.min(50,bid*.34),10);ctx.fillRect(X+119,yy-5,Math.min(50,ask*.34),10);ctx.fillStyle=i===0?'#eff0f1':'#aaa6ad';ctx.fillText(fmt(p,4),X+4,yy+3);ctx.fillStyle='#69c99c';ctx.fillText(String(bid),X+72,yy+3);ctx.fillStyle='#de7084';ctx.fillText(String(ask),X+124,yy+3)}}
 if(layers.volume){const top=H-lower+14,h=44,mx=Math.max(1,...vis.map(z=>z.v||1));ctx.fillStyle='#68636c';ctx.fillText('VOLUME',L,top-4);vis.forEach((b,i)=>{const q=(b.v||1)/mx*h;ctx.fillStyle=b.c>=b.o?'rgba(48,195,96,.72)':'rgba(113,53,154,.72)';ctx.fillRect(x(i)-2,top+h-q,4,q)})}
 if(layers.cvd){const top=H-66,h=48,mn=Math.min(...cv),mx=Math.max(...cv),spc=mx-mn||1,cy=v=>top+(mx-v)/spc*h;ctx.fillStyle='#6e6875';ctx.fillText('CVD',L,top-4);ctx.strokeStyle='#69409b';ctx.lineWidth=1.2;ctx.beginPath();cv.forEach((v,i)=>i?ctx.lineTo(x(i),cy(v)):ctx.moveTo(x(i),cy(v)));ctx.stroke()}
 if(cross){ctx.strokeStyle='rgba(220,220,225,.28)';ctx.setLineDash([3,4]);ctx.beginPath();ctx.moveTo(cross.x,T);ctx.lineTo(cross.x,H-8);ctx.moveTo(L,cross.y);ctx.lineTo(W-R,cross.y);ctx.stroke();ctx.setLineDash([])}
 },[bars,zoom,offset,cross,layers,mode,d]);
 const wheel=e=>{e.preventDefault();if(e.ctrlKey||e.metaKey)setZoom(z=>Math.max(18,Math.min(160,z+(e.deltaY>0?7:-7))));else setOffset(o=>Math.max(0,Math.min(Math.max(0,bars.length-18),o+(e.deltaY>0?3:-3))))};
 return <div className="nightChartOverlay"><div className="nightChartShell"><header className="nightChartHead"><div><small>NIGHT / DEEP ORDERFLOW WORKSPACE</small><h1>NIGHT CHART</h1><p>Heatmap · footprint · bubbles · DOM · gamma · volume profile · CVD</p></div><div className="nightChartControls"><select value={symbol} onChange={e=>setSymbol(e.target.value)}>{SYMBOLS.map(x=><option key={x}>{x}</option>)}</select><select value={tf} onChange={e=>setTf(e.target.value)}>{TFS.map(x=><option key={x}>{x}</option>)}</select><button onClick={load}>REFRESH</button><button onClick={onClose}>CLOSE</button></div></header><div className="nightChartBar"><b>{symbol}</b><span>{tf}</span><span>{status}</span>{['HEATMAP','FOOTPRINT','BUBBLES','CANDLE'].map(m=><button key={m} className={mode===m?'on':''} onClick={()=>setMode(m)}>{m}</button>)}{[['vp','VP'],['liq','LIQUIDITY'],['abs','ABSORPTION'],['dom','DOM'],['gamma','GAMMA'],['cvd','CVD'],['volume','VOL'],['vwap','VWAP']].map(([k,l])=><button key={k} className={layers[k]?'on':''} onClick={()=>toggle(k)}>{l}</button>)}</div>{err&&<div className="nightChartError">{err}</div>}<div className="nightWorkspace"><aside className="nightTools"><button title="Pointer">↖</button><button title="Crosshair">＋</button><button title="Horizontal line">━</button><button title="Trend line">╱</button><button title="Rectangle">□</button><button title="Fibonacci">Φ</button><button title="Measure">↔</button></aside><div className="nightCanvasWrap" onWheel={wheel} onMouseDown={e=>drag.current={x:e.clientX,o:offset}} onMouseMove={e=>{const r=e.currentTarget.getBoundingClientRect();setCross({x:e.clientX-r.left,y:e.clientY-r.top});if(drag.current)setOffset(Math.max(0,drag.current.o+Math.round(-(e.clientX-drag.current.x)/8)))}} onMouseUp={()=>drag.current=null} onMouseLeave={()=>{drag.current=null;setCross(null)}}><canvas ref={canvas}/></div></div><footer>FX/metals depth, footprint, absorption, liquidity and gamma marked * are derived L1/tick proxies when centralized L2/options data is unavailable. Visual density mirrors a deep orderflow workstation without mislabeling proxy data as exchange truth.</footer></div></div>}
