import React,{useEffect,useMemo,useRef,useState}from'react';
const API=import.meta.env.VITE_API_URL||'';
const SYMBOLS=['XAUUSD','XAGUSD','EURUSD','GBPUSD','USDJPY','USDCHF','USDCAD','AUDUSD','NZDUSD','EURJPY','GBPJPY','BTCUSD','ETHUSD','NAS100','SPX500','US30'];
const TFS=['1m','5m','15m','30m','1h','4h','1D'];
const creds=()=>{try{return JSON.parse(localStorage.getItem('night_quant_creds')||'{}')}catch{return{}}};
const n=(v,d=2)=>Number.isFinite(+v)?(+v).toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const norm=(a=[])=>a.map((b,i)=>({t:new Date(b.time||b.datetime||b.timestamp||Date.now()+i*6e4).getTime(),o:+(b.open??b.o),h:+(b.high??b.h),l:+(b.low??b.l),c:+(b.close??b.c),v:+(b.volume??b.tick_volume??b.tickVolume??0)})).filter(b=>[b.o,b.h,b.l,b.c].every(Number.isFinite));
function profile(a,bins=36){if(!a.length)return[];const lo=Math.min(...a.map(x=>x.l)),hi=Math.max(...a.map(x=>x.h)),s=(hi-lo||1)/bins,r=Array.from({length:bins},(_,i)=>({p:lo+(i+.5)*s,q:0,buy:0,sell:0}));a.forEach(x=>{const z=r[Math.max(0,Math.min(bins-1,Math.floor((x.c-lo)/s)))],q=x.v||1;z.q+=q;x.c>=x.o?z.buy+=q:z.sell+=q});return r}
function vwap(a){let pv=0,v=0;return a.map(x=>{const q=x.v||1;pv+=(x.h+x.l+x.c)/3*q;v+=q;return pv/v})}
function abs(a){if(a.length<6)return[];const av=a.reduce((s,x)=>s+(x.v||1),0)/a.length,r=[];a.forEach((x,i)=>{const rg=Math.max(1e-9,x.h-x.l),q=(x.v||1)/Math.max(1,av),up=(x.h-Math.max(x.o,x.c))/rg,dn=(Math.min(x.o,x.c)-x.l)/rg;for(const [side,w,p] of [['SELL',up,x.h],['BUY',dn,x.l]])if(w>.22&&q*w>.42)r.push({i,side,p,score:q*w})});return r.slice(-80)}
function footprint(b){const q=Math.max(1,b.v||1),range=Math.max(1e-9,b.h-b.l),pos=(b.c-b.l)/range,buy=Math.round(q*(.25+.5*pos)),sell=Math.max(0,Math.round(q-buy));return{buy,sell,delta:buy-sell}}
export default function NightChartDesk({onClose}){
 const[symbol,setSymbol]=useState('XAUUSD'),[tf,setTf]=useState('5m'),[bars,setBars]=useState([]),[status,setStatus]=useState('LOADING'),[err,setErr]=useState(''),[zoom,setZoom]=useState(72),[offset,setOffset]=useState(0),[cross,setCross]=useState(null),[mode,setMode]=useState('CANDLE'),[layers,setLayers]=useState({vp:true,vwap:true,liq:true,abs:true,dom:true,gamma:true});
 const canvas=useRef(null),drag=useRef(null);const toggle=k=>setLayers(x=>({...x,[k]:!x[k]}));
 async function load(){setStatus('LOADING');setErr('');try{const r=await fetch(API+'/api/bars',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({symbol,timeframe:tf,credentials:creds()})}),t=await r.text();let j={};try{j=JSON.parse(t)}catch{}if(!r.ok)throw Error(j.detail||t||`HTTP ${r.status}`);const b=norm(j.bars||[]);if(!b.length)throw Error('No OHLC bars returned');setBars(b);setOffset(0);setStatus((j.source||'MARKET DATA').toUpperCase())}catch(e){setErr(e.message);setStatus('NO DATA')}}
 useEffect(()=>{load();const id=setInterval(load,12000);return()=>clearInterval(id)},[symbol,tf]);
 const d=useMemo(()=>({vw:vwap(bars),abs:abs(bars)}),[bars]);
 useEffect(()=>{const c=canvas.current;if(!c||!bars.length)return;const ctx=c.getContext('2d'),D=Math.max(1,devicePixelRatio||1),r=c.getBoundingClientRect();c.width=r.width*D;c.height=r.height*D;ctx.setTransform(D,0,0,D,0,0);const W=r.width,H=r.height,L=52,R=layers.dom?196:82,T=24,B=54,PW=W-L-R,PH=H-T-B,count=Math.max(18,Math.min(bars.length,zoom)),end=Math.max(count,bars.length-offset),start=Math.max(0,end-count),vis=bars.slice(start,end),vw=d.vw.slice(start,end),lo=Math.min(...vis.map(x=>x.l)),hi=Math.max(...vis.map(x=>x.h)),sp=hi-lo||1,x=i=>L+(i+.5)*PW/vis.length,y=p=>T+(hi-p)/sp*PH;ctx.fillStyle='#08070b';ctx.fillRect(0,0,W,H);ctx.font='10px ui-monospace,monospace';for(let i=0;i<=8;i++){const yy=T+i*PH/8;ctx.strokeStyle='#201c26';ctx.beginPath();ctx.moveTo(L,yy);ctx.lineTo(W-R,yy);ctx.stroke();ctx.fillStyle='#746d7c';ctx.fillText(n(hi-i*sp/8,4),W-R+7,yy+3)}for(let i=0;i<=10;i++){const xx=L+i*PW/10;ctx.strokeStyle='#17151b';ctx.beginPath();ctx.moveTo(xx,T);ctx.lineTo(xx,H-B);ctx.stroke()}
 const prof=profile(vis,42),mx=Math.max(1,...prof.map(z=>z.q));if(layers.liq)prof.forEach(z=>{const a=z.q/mx,yy=y(z.p);ctx.fillStyle=`rgba(116,72,196,${.035+a*.30})`;ctx.fillRect(L,yy-5,PW,10);if(a>.72){ctx.fillStyle=`rgba(205,174,255,${.15+a*.25})`;ctx.fillRect(L,yy-1,PW,2)}});
 const cw=Math.max(3,Math.min(mode==='FOOTPRINT'?34:12,PW/vis.length*.72));vis.forEach((b,i)=>{const xx=x(i),up=b.c>=b.o;if(mode==='FOOTPRINT'&&cw>18){const f=footprint(b),top=y(b.h),bot=y(b.l),hh=Math.max(13,bot-top);ctx.fillStyle='rgba(16,13,20,.88)';ctx.fillRect(xx-cw/2,top,cw,hh);ctx.strokeStyle=f.delta>=0?'#3bcaa5':'#f05d77';ctx.strokeRect(xx-cw/2,top,cw,hh);ctx.font='8px ui-monospace';ctx.fillStyle='#d9d3df';ctx.fillText(`${f.sell}×${f.buy}`,xx-cw/2+2,top+10);ctx.fillStyle=f.delta>=0?'#4ddbb6':'#ff7188';ctx.fillText(`${f.delta>=0?'+':''}${f.delta}`,xx-cw/2+2,Math.min(bot-2,top+21))}else{ctx.strokeStyle=up?'#36c7a5':'#ef5c76';ctx.fillStyle=ctx.strokeStyle;ctx.beginPath();ctx.moveTo(xx,y(b.h));ctx.lineTo(xx,y(b.l));ctx.stroke();ctx.fillRect(xx-cw/2,Math.min(y(b.o),y(b.c)),cw,Math.max(1,Math.abs(y(b.o)-y(b.c))))}});
 if(layers.vwap){ctx.strokeStyle='#b795ff';ctx.lineWidth=1.4;ctx.beginPath();vw.forEach((p,i)=>i?ctx.lineTo(x(i),y(p)):ctx.moveTo(x(i),y(p)));ctx.stroke()}
 if(layers.vp)prof.forEach(z=>{const yy=y(z.p),w=z.q/mx*92;ctx.fillStyle='rgba(188,157,255,.48)';ctx.fillRect(L,yy-2,w,4)});
 if(layers.abs)d.abs.filter(a=>a.i>=start&&a.i<end).forEach(a=>{const xx=x(a.i-start),yy=y(a.p),rad=Math.min(17,3+a.score*3);ctx.strokeStyle=a.side==='BUY'?'rgba(72,224,177,.5)':'rgba(255,92,126,.5)';ctx.beginPath();ctx.moveTo(xx,yy);ctx.lineTo(W-R,yy);ctx.stroke();ctx.fillStyle=a.side==='BUY'?'#48ddb1':'#ff617d';ctx.beginPath();ctx.arc(xx,yy,rad,0,Math.PI*2);ctx.fill();ctx.fillStyle='#08070b';ctx.font='bold 8px ui-monospace';ctx.fillText(a.side==='BUY'?'B':'S',xx-3,yy+3)});
 if(layers.gamma){const last=vis.at(-1)?.c||0;[-.006,-.003,.003,.006].forEach((m,i)=>{const p=last*(1+m),yy=y(p);if(yy<T||yy>H-B)return;ctx.setLineDash([6,5]);ctx.strokeStyle=i<2?'rgba(255,93,126,.42)':'rgba(155,124,255,.48)';ctx.beginPath();ctx.moveTo(L,yy);ctx.lineTo(W-R,yy);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#a99bb9';ctx.fillText(i===0?'PUT WALL*':i===3?'CALL WALL*':'GEX*',L+6,yy-3)})}
 if(layers.dom){const X=W-R+72,mid=vis.at(-1)?.c||0,step=sp/30;ctx.fillStyle='#0d0b11';ctx.fillRect(W-R,T,R,H-T-B);ctx.fillStyle='#8d8297';ctx.fillText('DOM · L1/PROXY',W-R+8,T+14);for(let i=-9;i<=9;i++){const p=mid-i*step,yy=y(p),q=Math.round(20+Math.abs(Math.sin(p*17))*180);ctx.fillStyle=i<0?'rgba(48,190,151,.18)':'rgba(239,86,116,.18)';ctx.fillRect(X,yy-5,Math.min(75,q/2),10);ctx.fillStyle=i===0?'#e9dfff':'#9b929f';ctx.fillText(n(p,4),W-R+8,yy+3);ctx.fillText(String(q),X+4,yy+3)}}
 if(cross){ctx.setLineDash([3,4]);ctx.strokeStyle='rgba(220,210,235,.32)';ctx.beginPath();ctx.moveTo(cross.x,T);ctx.lineTo(cross.x,H-B);ctx.moveTo(L,cross.y);ctx.lineTo(W-R,cross.y);ctx.stroke();ctx.setLineDash([])}
 },[bars,zoom,offset,cross,layers,mode,d]);
 const wheel=e=>{e.preventDefault();if(e.ctrlKey||e.metaKey)setZoom(z=>Math.max(18,Math.min(180,z+(e.deltaY>0?8:-8))));else setOffset(o=>Math.max(0,Math.min(Math.max(0,bars.length-18),o+(e.deltaY>0?3:-3))))};
 return <div className="nightChartOverlay"><div className="nightChartShell"><header className="nightChartHead"><div><small>NIGHT MICROSTRUCTURE TERMINAL</small><h1>NIGHT CHART</h1><p>Deep charting workspace · candles · footprint · liquidity · absorption · DOM · gamma · volume profile</p></div><div className="nightChartControls"><select value={symbol} onChange={e=>setSymbol(e.target.value)}>{SYMBOLS.map(x=><option key={x}>{x}</option>)}</select><select value={tf} onChange={e=>setTf(e.target.value)}>{TFS.map(x=><option key={x}>{x}</option>)}</select><button onClick={load}>REFRESH</button><button onClick={onClose}>CLOSE</button></div></header><div className="nightChartBar"><b>{symbol}</b><span>{tf}</span><span>{status}</span><button className={mode==='CANDLE'?'on':''} onClick={()=>setMode('CANDLE')}>CANDLE</button><button className={mode==='FOOTPRINT'?'on':''} onClick={()=>setMode('FOOTPRINT')}>FOOTPRINT</button>{[['vp','VOLUME PROFILE'],['vwap','VWAP'],['liq','LIQUIDITY'],['abs','ABSORPTION'],['dom','DOM'],['gamma','GAMMA']].map(([k,l])=><button key={k} className={layers[k]?'on':''} onClick={()=>toggle(k)}>{l}</button>)}</div>{err&&<div className="nightChartError">{err}</div>}<div className="nightWorkspace"><aside className="nightTools"><button title="Crosshair">＋</button><button title="Horizontal line">━</button><button title="Trend line">╱</button><button title="Fibonacci">Φ</button><button title="Measure">↔</button></aside><div className="nightCanvasWrap" onWheel={wheel} onMouseDown={e=>drag.current={x:e.clientX,o:offset}} onMouseMove={e=>{const r=e.currentTarget.getBoundingClientRect();setCross({x:e.clientX-r.left,y:e.clientY-r.top});if(drag.current)setOffset(Math.max(0,drag.current.o+Math.round(-(e.clientX-drag.current.x)/8)))}} onMouseUp={()=>drag.current=null} onMouseLeave={()=>{drag.current=null;setCross(null)}}><canvas ref={canvas}/></div></div><footer>* FX/metals DOM, footprint, liquidity, absorption and gamma displays are explicitly proxy/derived where centralized L2/options data is unavailable. They are not fabricated as exchange truth. Crypto can use true exchange L2 in the Orderflow desk.</footer></div></div>}
