import React,{useEffect,useMemo,useRef,useState}from'react';

const API=import.meta.env.VITE_API_URL||'';
const SYMBOLS=['XAUUSD','XAGUSD','EURUSD','GBPUSD','USDJPY','USDCHF','USDCAD','AUDUSD','NZDUSD','EURJPY','GBPJPY','BTCUSD','ETHUSD','NAS100','SPX500','US30'];
const TFS=['1m','5m','15m','30m','1h','4h','1D'];
const creds=()=>{try{return JSON.parse(localStorage.getItem('night_quant_creds')||'{}')}catch{return{}}};
const num=(v,d=2)=>Number.isFinite(+v)?(+v).toLocaleString(undefined,{maximumFractionDigits:d}):'—';

function normalizeBars(rows=[]){return rows.map((b,i)=>({t:new Date(b.time||b.datetime||b.timestamp||Date.now()+i*60000).getTime(),o:+(b.open??b.o),h:+(b.high??b.h),l:+(b.low??b.l),c:+(b.close??b.c),v:+(b.volume??b.tick_volume??b.tickVolume??0)})).filter(b=>[b.o,b.h,b.l,b.c].every(Number.isFinite))}
function vwap(bars){let pv=0,v=0;return bars.map(b=>{const vol=b.v||1;pv+=((b.h+b.l+b.c)/3)*vol;v+=vol;return pv/v})}
function profile(bars,bins=32){if(!bars.length)return[];const lo=Math.min(...bars.map(b=>b.l)),hi=Math.max(...bars.map(b=>b.h)),step=(hi-lo||1)/bins,a=Array.from({length:bins},(_,i)=>({p:lo+(i+.5)*step,q:0}));bars.forEach(b=>{const idx=Math.max(0,Math.min(bins-1,Math.floor((b.c-lo)/step)));a[idx].q+=b.v||1});return a}
function absorptions(bars){if(bars.length<8)return[];const vols=bars.map(b=>b.v||1),avg=vols.reduce((a,b)=>a+b,0)/vols.length;return bars.map((b,i)=>{const range=Math.max(1e-9,b.h-b.l),body=Math.abs(b.c-b.o),wickRatio=1-body/range,score=(b.v||1)/Math.max(avg,1)*wickRatio;let side=null;if(score>1.7){if(b.c>=b.o&&(b.h-b.c)/range>.38)side='SELL';else if(b.c<b.o&&(b.c-b.l)/range>.38)side='BUY'}return side?{i,p:side==='SELL'?b.h:b.l,side,score}:null}).filter(Boolean).slice(-18)}

export default function NightChartDesk({onClose}){
 const[symbol,setSymbol]=useState('XAUUSD'),[tf,setTf]=useState('5m'),[bars,setBars]=useState([]),[status,setStatus]=useState('LOADING'),[err,setErr]=useState(''),[zoom,setZoom]=useState(90),[offset,setOffset]=useState(0),[cross,setCross]=useState(null),[showVP,setShowVP]=useState(true),[showVWAP,setShowVWAP]=useState(true),[showLiq,setShowLiq]=useState(true),[showAbs,setShowAbs]=useState(true);
 const canvasRef=useRef(null),drag=useRef(null);
 async function load(){setStatus('LOADING');setErr('');try{const r=await fetch(API+'/api/bars',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({symbol,timeframe:tf,credentials:creds()})});const text=await r.text();let j={};try{j=JSON.parse(text)}catch{};if(!r.ok)throw new Error(j.detail||text||`HTTP ${r.status}`);const b=normalizeBars(j.bars||[]);if(!b.length)throw new Error('No OHLC bars returned');setBars(b);setOffset(0);setStatus((j.source||'MARKET DATA').toUpperCase())}catch(e){setErr(e.message);setStatus('NO DATA')}}
 useEffect(()=>{load();const id=setInterval(load,15000);return()=>clearInterval(id)},[symbol,tf]);
 const derived=useMemo(()=>({vw:vwap(bars),vp:profile(bars),abs:absorptions(bars)}),[bars]);
 useEffect(()=>{const c=canvasRef.current;if(!c||!bars.length)return;const ctx=c.getContext('2d'),dpr=Math.max(1,window.devicePixelRatio||1),rect=c.getBoundingClientRect();c.width=Math.floor(rect.width*dpr);c.height=Math.floor(rect.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);const W=rect.width,H=rect.height,padL=58,padR=84,padT=18,padB=32,plotW=W-padL-padR,plotH=H-padT-padB,count=Math.max(25,Math.min(bars.length,zoom)),end=Math.max(count,bars.length-offset),start=Math.max(0,end-count),vis=bars.slice(start,end),vw=derived.vw.slice(start,end);const lo=Math.min(...vis.map(b=>b.l)),hi=Math.max(...vis.map(b=>b.h)),span=(hi-lo)||1,px=i=>padL+(i+.5)*(plotW/vis.length),py=p=>padT+(hi-p)/span*plotH;ctx.clearRect(0,0,W,H);ctx.fillStyle='#0b0910';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#24202d';ctx.lineWidth=1;ctx.font='10px ui-monospace,monospace';ctx.fillStyle='#837a91';for(let i=0;i<=6;i++){const y=padT+i*plotH/6;ctx.beginPath();ctx.moveTo(padL,y);ctx.lineTo(W-padR,y);ctx.stroke();ctx.fillText(num(hi-i*span/6,4),W-padR+8,y+3)}for(let i=0;i<=8;i++){const x=padL+i*plotW/8;ctx.beginPath();ctx.moveTo(x,padT);ctx.lineTo(x,H-padB);ctx.stroke()}
 if(showLiq){const prof=profile(vis,28),mx=Math.max(1,...prof.map(x=>x.q));prof.forEach(r=>{const y=py(r.p),w=(r.q/mx)*plotW*.42;ctx.fillStyle=`rgba(147,92,255,${.04+.22*r.q/mx})`;ctx.fillRect(W-padR-w,y-5,w,10)})}
 const cw=Math.max(2,Math.min(12,plotW/vis.length*.68));vis.forEach((b,i)=>{const x=px(i),up=b.c>=b.o;ctx.strokeStyle=up?'#30c7a6':'#ff5869';ctx.fillStyle=up?'#30c7a6':'#ff5869';ctx.beginPath();ctx.moveTo(x,py(b.h));ctx.lineTo(x,py(b.l));ctx.stroke();const y=Math.min(py(b.o),py(b.c)),h=Math.max(1,Math.abs(py(b.o)-py(b.c)));ctx.fillRect(x-cw/2,y,cw,h)});
 if(showVWAP&&vw.length){ctx.strokeStyle='#c8a8ff';ctx.lineWidth=1.5;ctx.beginPath();vw.forEach((p,i)=>{const x=px(i),y=py(p);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}
 if(showVP){const prof=profile(vis,30),mx=Math.max(1,...prof.map(x=>x.q));prof.forEach(r=>{const y=py(r.p);ctx.fillStyle='rgba(177,148,255,.35)';ctx.fillRect(padL,y-2,(r.q/mx)*74,4)})}
 if(showAbs){derived.abs.filter(a=>a.i>=start&&a.i<end).forEach(a=>{const i=a.i-start,x=px(i),y=py(a.p);ctx.strokeStyle=a.side==='BUY'?'#55dfaf':'#ff6d8a';ctx.setLineDash([4,4]);ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(W-padR,y);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=a.side==='BUY'?'#55dfaf':'#ff6d8a';ctx.beginPath();ctx.arc(x,y,Math.min(14,5+a.score*2),0,Math.PI*2);ctx.fill();ctx.fillStyle='#0b0910';ctx.font='bold 9px ui-monospace';ctx.fillText(a.side==='BUY'?'B':'S',x-3,y+3)})}
 if(cross){ctx.strokeStyle='rgba(220,210,240,.35)';ctx.setLineDash([3,4]);ctx.beginPath();ctx.moveTo(cross.x,padT);ctx.lineTo(cross.x,H-padB);ctx.moveTo(padL,cross.y);ctx.lineTo(W-padR,cross.y);ctx.stroke();ctx.setLineDash([]);const price=hi-(cross.y-padT)/plotH*span;ctx.fillStyle='#c7b8e3';ctx.fillText(num(price,5),W-padR+8,cross.y+3)}
 },[bars,zoom,offset,cross,showVP,showVWAP,showLiq,showAbs,derived]);
 const wheel=e=>{e.preventDefault();if(e.ctrlKey||e.metaKey)setZoom(z=>Math.max(25,Math.min(220,z+(e.deltaY>0?10:-10))));else setOffset(o=>Math.max(0,Math.min(Math.max(0,bars.length-25),o+(e.deltaY>0?4:-4))))};
 return <div className="nightChartOverlay"><div className="nightChartShell"><header className="nightChartHead"><div><small>NIGHT PROPRIETARY CHART ENGINE</small><h1>NIGHT CHART</h1><p>Custom Canvas chart · no TradingView embed · provider-backed OHLC only.</p></div><div className="nightChartControls"><select value={symbol} onChange={e=>setSymbol(e.target.value)}>{SYMBOLS.map(x=><option key={x}>{x}</option>)}</select><select value={tf} onChange={e=>setTf(e.target.value)}>{TFS.map(x=><option key={x}>{x}</option>)}</select><button onClick={load}>REFRESH</button><button onClick={onClose}>CLOSE</button></div></header><div className="nightChartBar"><b>{symbol}</b><span>{tf}</span><span>{status}</span><button className={showVP?'on':''} onClick={()=>setShowVP(v=>!v)}>VP</button><button className={showVWAP?'on':''} onClick={()=>setShowVWAP(v=>!v)}>VWAP</button><button className={showLiq?'on':''} onClick={()=>setShowLiq(v=>!v)}>LIQUIDITY</button><button className={showAbs?'on':''} onClick={()=>setShowAbs(v=>!v)}>ABSORPTION</button><small>Wheel = pan · Ctrl/⌘ + wheel = zoom</small></div>{err&&<div className="nightChartError">{err}</div>}<div className="nightCanvasWrap" onWheel={wheel} onMouseDown={e=>drag.current={x:e.clientX,o:offset}} onMouseMove={e=>{const r=e.currentTarget.getBoundingClientRect();setCross({x:e.clientX-r.left,y:e.clientY-r.top});if(drag.current){const dx=e.clientX-drag.current.x;setOffset(Math.max(0,drag.current.o+Math.round(-dx/8)))}}} onMouseUp={()=>drag.current=null} onMouseLeave={()=>{drag.current=null;setCross(null)}}><canvas ref={canvasRef}/></div><footer>Liquidity and absorption on FX/metals are Level-1/tick-volume proxies derived from provider OHLC/tick volume. Crypto can be upgraded to true L2 overlay independently in the Orderflow desk.</footer></div></div>
}
