import React,{useEffect,useMemo,useRef,useState}from'react';
import{HubConnectionBuilder,LogLevel}from'@microsoft/signalr';
import TradingViewChart from'./TradingViewChart';

const ASSETS=['BTCUSD','ETHUSD','XAUUSD','XAGUSD','EURUSD','GBPUSD','USDJPY','USDCHF','USDCAD','AUDUSD','NZDUSD','EURJPY','GBPJPY','EURGBP','AUDJPY','NAS100','SPX500','US30','SPY','QQQ','DIA','AAPL','NVDA','TSLA','META','AMD'];
const BINANCE={BTCUSD:'btcusdt',ETHUSD:'ethusdt'};
const FXCFD=new Set(['XAUUSD','XAGUSD','EURUSD','GBPUSD','USDJPY','USDCHF','USDCAD','AUDUSD','NZDUSD','EURJPY','GBPJPY','EURGBP','AUDJPY']);
const GAMMA_PROXY={XAUUSD:'GLD',XAGUSD:'SLV',NAS100:'QQQ',SPX500:'SPY',US30:'DIA',SPY:'SPY',QQQ:'QQQ',DIA:'DIA',AAPL:'AAPL',NVDA:'NVDA',TSLA:'TSLA',META:'META',AMD:'AMD'};
const GAMMA_URL='https://algoxflow.com/api/gexmap?ticker=';
const n=(v,d=2)=>v==null||Number.isNaN(Number(v))?'—':Number(v).toLocaleString(undefined,{maximumFractionDigits:d});

function Spark({trades}){const pts=useMemo(()=>{if(trades.length<2)return'';const xs=trades.slice(-180),prices=xs.map(x=>x.p),lo=Math.min(...prices),hi=Math.max(...prices),span=hi-lo||1;return xs.map((x,i)=>`${(i/(xs.length-1))*100},${95-((x.p-lo)/span)*85}`).join(' ')},[trades]);return <svg className="ofSpark" viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points={pts}/></svg>}
function Heatmap({bids,asks}){const rows=[...asks.slice(0,20).reverse().map(x=>({...x,side:'ASK'})),...bids.slice(0,20).map(x=>({...x,side:'BID'}))];const max=Math.max(1,...rows.map(x=>x.q));return <div className="depthHeat">{rows.map((r,i)=><div className={`depthRow ${r.side.toLowerCase()}`} key={`${r.side}-${r.p}-${i}`}><i style={{width:`${Math.min(100,(r.q/max)*100)}%`}}/><span>{r.side}</span><b>{n(r.p,5)}</b><em>{n(r.q,4)}</em></div>)}</div>}
function TickHeatmap({ticks}){const rows=useMemo(()=>{if(!ticks.length)return[];const ps=ticks.map(x=>x.p),lo=Math.min(...ps),hi=Math.max(...ps),step=(hi-lo||Math.max(Math.abs(ps[0])*.00005,.00001))/16;const bins=new Map();ticks.forEach(t=>{const k=Math.round((t.p-lo)/step),px=lo+k*step,b=bins.get(k)||{p:px,up:0,down:0,total:0};b[t.side==='BUY'?'up':'down']++;b.total++;bins.set(k,b)});return[...bins.values()].sort((a,b)=>b.p-a.p)},[ticks]);const max=Math.max(1,...rows.map(x=>x.total));if(!rows.length)return <div className="ofEmpty">Waiting for BiQuote FX/CFD ticks…</div>;return <div className="depthHeat proxyHeat">{rows.map((r,i)=>{const side=r.up>=r.down?'BID':'ASK';return <div className={`depthRow ${side.toLowerCase()}`} key={i}><i style={{width:`${r.total/max*100}%`}}/><span>{side==='BID'?'UP TICKS':'DOWN TICKS'}</span><b>{n(r.p,5)}</b><em>{r.total} ticks</em></div>})}</div>}
function GammaChart({data}){const rows=(data?.byStrike||data?.strikes||data?.gammaByStrike||[]).slice(0,80);if(!rows.length)return <div className="ofEmpty">No strike-level gamma array returned by provider.</div>;const vals=rows.map(r=>Number(r.netGamma??r.gex??r.gamma??r.net_gex??0));const max=Math.max(1,...vals.map(Math.abs));return <div className="gammaBars">{rows.map((r,i)=>{const strike=r.strike??r.k??r.price,val=vals[i];return <div key={`${strike}-${i}`}><span>{n(strike,2)}</span><i className={val>=0?'pos':'neg'} style={{width:`${Math.min(100,Math.abs(val)/max*100)}%`}}/><b>{n(val,0)}</b></div>})}</div>}

export default function OrderflowDesk({onClose}){
 const[symbol,setSymbol]=useState('BTCUSD'),[book,setBook]=useState({bids:[],asks:[]}),[trades,setTrades]=useState([]),[status,setStatus]=useState('CONNECTING'),[gamma,setGamma]=useState(null),[gammaErr,setGammaErr]=useState('');
 const wsRef=useRef(null),signalRef=useRef(null),prevMid=useRef(null);const gammaTicker=GAMMA_PROXY[symbol],exchangeSym=BINANCE[symbol],isFx=FXCFD.has(symbol);
 useEffect(()=>{setBook({bids:[],asks:[]});setTrades([]);prevMid.current=null;if(wsRef.current)try{wsRef.current.close()}catch{};if(signalRef.current)try{signalRef.current.stop()}catch{};
  if(exchangeSym){const ws=new WebSocket(`wss://stream.binance.com:9443/stream?streams=${exchangeSym}@depth20@100ms/${exchangeSym}@aggTrade`);wsRef.current=ws;ws.onopen=()=>setStatus('LIVE BINANCE L2');ws.onerror=()=>setStatus('BINANCE STREAM ERROR');ws.onclose=()=>setStatus(s=>s.includes('ERROR')?s:'DISCONNECTED');ws.onmessage=e=>{try{const m=JSON.parse(e.data),d=m.data||{};if(m.stream?.includes('@depth20'))setBook({bids:(d.bids||[]).map(x=>({p:+x[0],q:+x[1]})),asks:(d.asks||[]).map(x=>({p:+x[0],q:+x[1]}))});else if(m.stream?.includes('@aggTrade'))setTrades(t=>[...t.slice(-399),{p:+d.p,q:+d.q,t:d.T,side:d.m?'SELL':'BUY',m:d.m}])}catch{}};return()=>{try{ws.close()}catch{}}}
  if(isFx){let dead=false;const conn=new HubConnectionBuilder().withUrl('https://biquote.io/hubs/tick').withAutomaticReconnect().configureLogging(LogLevel.None).build();signalRef.current=conn;conn.on('ReceiveTick',tick=>{if(dead||String(tick.symbol||'').toUpperCase()!==symbol)return;const mid=Number(tick.mid)||((Number(tick.bid)+Number(tick.ask))/2),bid=Number(tick.bid),ask=Number(tick.ask);if(!Number.isFinite(mid))return;const side=prevMid.current==null?'FLAT':mid>prevMid.current?'BUY':mid<prevMid.current?'SELL':'FLAT';prevMid.current=mid;setBook({bids:Number.isFinite(bid)?[{p:bid,q:1}]:[],asks:Number.isFinite(ask)?[{p:ask,q:1}]:[]});setTrades(t=>[...t.slice(-399),{p:mid,q:1,t:Date.parse(tick.timestamp)||Date.now(),side,source:tick.source,spread:Number(tick.spread)}])});conn.start().then(()=>conn.invoke('Subscribe',[symbol])).then(()=>!dead&&setStatus('LIVE BIQUOTE TICK FLOW PROXY')).catch(()=>!dead&&setStatus('BIQUOTE STREAM ERROR'));return()=>{dead=true;try{conn.stop()}catch{}}}
  setStatus('NO FREE ORDERFLOW FEED');
 },[symbol,exchangeSym,isFx]);
 useEffect(()=>{let dead=false;setGamma(null);setGammaErr('');if(!gammaTicker)return;fetch(GAMMA_URL+encodeURIComponent(gammaTicker)).then(async r=>{const text=await r.text();let j;try{j=JSON.parse(text)}catch{throw new Error(text.slice(0,120)||`HTTP ${r.status}`)}if(!r.ok)throw new Error(j.detail||j.error||`HTTP ${r.status}`);if(!dead)setGamma(j)}).catch(e=>!dead&&setGammaErr(e.message));return()=>{dead=true}},[gammaTicker]);
 const buyVol=trades.filter(x=>x.side==='BUY').reduce((a,b)=>a+b.q,0),sellVol=trades.filter(x=>x.side==='SELL').reduce((a,b)=>a+b.q,0),delta=buyVol-sellVol,bestBid=book.bids[0]?.p,bestAsk=book.asks[0]?.p,spread=bestBid&&bestAsk?bestAsk-bestBid:(trades.at(-1)?.spread??null),mode=exchangeSym?'TRUE EXCHANGE L2':isFx?'FX/CFD TICK-FLOW PROXY':'NO FLOW';
 return <div className="ofOverlay"><div className="ofShell"><div className="ofHead"><div><small>NIGHT MICROSTRUCTURE LAB</small><h1>ORDERFLOW · HEATMAP · GAMMA</h1><p>Crypto uses true exchange L2. FX/gold uses free BiQuote MT5 bid/ask tick-flow and tick-density proxy, clearly labelled because spot FX has no centralized global book.</p></div><div><select value={symbol} onChange={e=>setSymbol(e.target.value)}>{ASSETS.map(x=><option key={x}>{x}</option>)}</select><button onClick={onClose}>CLOSE</button></div></div>
  <div className="ofStatus"><b>{symbol}</b><span>{status}</span><span>{mode}</span><span>Gamma {gammaTicker?`via ${gammaTicker}`:'NO OPTIONS PROXY'}</span></div>
  <div className="ofGrid"><section className="ofPanel chart"><h3>FULL MARKET CHART</h3><div className="ofChart"><TradingViewChart symbol={symbol} interval="1"/></div></section><section className="ofPanel"><h3>{isFx?'LIVE FX / GOLD TICK FLOW':'LIVE ORDERFLOW'}</h3>{exchangeSym||isFx?<><div className="ofMetrics"><div><span>Best bid</span><b>{n(bestBid,5)}</b></div><div><span>Best ask</span><b>{n(bestAsk,5)}</b></div><div><span>Spread</span><b>{n(spread,5)}</b></div><div><span>{isFx?'Tick delta':'Trade delta'}</span><b>{n(delta,0)}</b></div><div><span>Up ticks</span><b>{n(buyVol,0)}</b></div><div><span>Down ticks</span><b>{n(sellVol,0)}</b></div></div><Spark trades={trades}/><div className="flowTape">{trades.slice(-24).reverse().map((t,i)=><div className={t.side==='SELL'?'sell':'buy'} key={i}><span>{t.side}</span><b>{n(t.p,5)}</b><em>{isFx?'tick':n(t.q,5)}</em></div>)}</div>{isFx&&<p className="ofNote">Proxy methodology: aggressor direction is inferred from mid-price tick direction; density is tick count by price. It is not centralized Level 2 liquidity.</p>}</>:<div className="ofEmpty">No free flow source configured for this instrument.</div>}</section><section className="ofPanel"><h3>{isFx?'TICK-DENSITY HEATMAP':'ORDER BOOK HEATMAP'}</h3>{exchangeSym?<Heatmap bids={book.bids} asks={book.asks}/>:isFx?<TickHeatmap ticks={trades}/>:<div className="ofEmpty">No free depth feed for this symbol.</div>}</section><section className="ofPanel gamma"><h3>GAMMA EXPOSURE</h3>{gammaErr?<div className="ofEmpty">Gamma provider error: {gammaErr}</div>:gamma?<><div className="ofMetrics"><div><span>Underlying</span><b>{gamma.ticker||gammaTicker}</b></div><div><span>Spot</span><b>{n(gamma.spot,2)}</b></div><div><span>Regime</span><b>{gamma.regime||gamma.gammaRegime||'—'}</b></div><div><span>Zero gamma</span><b>{n(gamma.zeroGamma??gamma.zero_gamma??gamma.gammaFlip,2)}</b></div><div><span>Call wall</span><b>{n(gamma.callWall??gamma.call_wall,2)}</b></div><div><span>Put wall</span><b>{n(gamma.putWall??gamma.put_wall,2)}</b></div></div><GammaChart data={gamma}/><p className="ofNote">Metals/indices use labelled liquid options proxies: XAUUSD→GLD, XAGUSD→SLV, NAS100→QQQ, SPX500→SPY.</p></>:<div className="ofEmpty">{gammaTicker?'Loading gamma feed…':'No liquid US options proxy configured for this symbol.'}</div>}</section></div>
  <footer>Sources: Binance public WebSocket for crypto L2/trades; BiQuote public SignalR for FX/metals bid/ask ticks; AlgoXFlow gamma for supported US options/proxies. FX/metals tick-flow is a broker-feed proxy, not a centralized global order book.</footer>
 </div></div>
}
