import React,{useEffect,useMemo,useRef,useState}from'react';
import TradingViewChart from'./TradingViewChart';

const ASSETS=['BTCUSD','ETHUSD','XAUUSD','NAS100','SPX500','US30','SPY','QQQ','DIA','AAPL','NVDA','TSLA','META','AMD'];
const BINANCE={BTCUSD:'btcusdt',ETHUSD:'ethusdt'};
const GAMMA_PROXY={XAUUSD:'GLD',NAS100:'QQQ',SPX500:'SPY',US30:'DIA',SPY:'SPY',QQQ:'QQQ',DIA:'DIA',AAPL:'AAPL',NVDA:'NVDA',TSLA:'TSLA',META:'META',AMD:'AMD'};
const GAMMA_URL='https://algoxflow.com/api/gexmap?ticker=';
const n=(v,d=2)=>v==null||Number.isNaN(Number(v))?'—':Number(v).toLocaleString(undefined,{maximumFractionDigits:d});

function Spark({trades}){const pts=useMemo(()=>{if(trades.length<2)return'';const xs=trades.slice(-180),prices=xs.map(x=>x.p),lo=Math.min(...prices),hi=Math.max(...prices),span=hi-lo||1;return xs.map((x,i)=>`${(i/(xs.length-1))*100},${95-((x.p-lo)/span)*85}`).join(' ')},[trades]);return <svg className="ofSpark" viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points={pts}/></svg>}
function Heatmap({bids,asks}){const rows=[...asks.slice(0,20).reverse().map(x=>({...x,side:'ASK'})),...bids.slice(0,20).map(x=>({...x,side:'BID'}))];const max=Math.max(1,...rows.map(x=>x.q));return <div className="depthHeat">{rows.map((r,i)=><div className={`depthRow ${r.side.toLowerCase()}`} key={`${r.side}-${r.p}-${i}`}><i style={{width:`${Math.min(100,(r.q/max)*100)}%`}}/><span>{r.side}</span><b>{n(r.p,2)}</b><em>{n(r.q,4)}</em></div>)}</div>}
function GammaChart({data}){const rows=(data?.byStrike||data?.strikes||data?.gammaByStrike||[]).slice(0,80);if(!rows.length)return <div className="ofEmpty">No strike-level gamma array returned by provider.</div>;const vals=rows.map(r=>Number(r.netGamma??r.gex??r.gamma??r.net_gex??0));const max=Math.max(1,...vals.map(Math.abs));return <div className="gammaBars">{rows.map((r,i)=>{const strike=r.strike??r.k??r.price;const val=vals[i];return <div key={`${strike}-${i}`}><span>{n(strike,2)}</span><i className={val>=0?'pos':'neg'} style={{width:`${Math.min(100,Math.abs(val)/max*100)}%`}}/><b>{n(val,0)}</b></div>})}</div>}

export default function OrderflowDesk({onClose}){
 const[symbol,setSymbol]=useState('BTCUSD'),[book,setBook]=useState({bids:[],asks:[]}),[trades,setTrades]=useState([]),[status,setStatus]=useState('CONNECTING'),[gamma,setGamma]=useState(null),[gammaErr,setGammaErr]=useState('');
 const wsRef=useRef(null);const gammaTicker=GAMMA_PROXY[symbol];const exchangeSym=BINANCE[symbol];
 useEffect(()=>{setBook({bids:[],asks:[]});setTrades([]);if(wsRef.current)try{wsRef.current.close()}catch{};if(!exchangeSym){setStatus('NO CENTRALIZED ORDER BOOK');return}
  const ws=new WebSocket(`wss://stream.binance.com:9443/stream?streams=${exchangeSym}@depth20@100ms/${exchangeSym}@aggTrade`);wsRef.current=ws;ws.onopen=()=>setStatus('LIVE BINANCE ORDER BOOK');ws.onerror=()=>setStatus('STREAM ERROR');ws.onclose=()=>setStatus(s=>s==='STREAM ERROR'?s:'DISCONNECTED');ws.onmessage=e=>{try{const m=JSON.parse(e.data),d=m.data||{};if(m.stream?.includes('@depth20')){setBook({bids:(d.bids||[]).map(x=>({p:+x[0],q:+x[1]})),asks:(d.asks||[]).map(x=>({p:+x[0],q:+x[1]}))})}else if(m.stream?.includes('@aggTrade')){setTrades(t=>[...t.slice(-249),{p:+d.p,q:+d.q,t:d.T,m:d.m}])}}catch{}};return()=>{try{ws.close()}catch{}}
 },[exchangeSym]);
 useEffect(()=>{let dead=false;setGamma(null);setGammaErr('');if(!gammaTicker)return;fetch(GAMMA_URL+encodeURIComponent(gammaTicker)).then(async r=>{const text=await r.text();let j;try{j=JSON.parse(text)}catch{throw new Error(text.slice(0,120)||`HTTP ${r.status}`)}if(!r.ok)throw new Error(j.detail||j.error||`HTTP ${r.status}`);if(!dead)setGamma(j)}).catch(e=>!dead&&setGammaErr(e.message));return()=>{dead=true}},[gammaTicker]);
 const buyVol=trades.filter(x=>!x.m).reduce((a,b)=>a+b.q,0),sellVol=trades.filter(x=>x.m).reduce((a,b)=>a+b.q,0),delta=buyVol-sellVol;const bestBid=book.bids[0]?.p,bestAsk=book.asks[0]?.p,spread=bestBid&&bestAsk?bestAsk-bestBid:null;
 return <div className="ofOverlay"><div className="ofShell"><div className="ofHead"><div><small>NIGHT MICROSTRUCTURE LAB</small><h1>ORDERFLOW · HEATMAP · GAMMA</h1><p>True order book where a public exchange feed exists. No synthetic FX/XAU order book.</p></div><div><select value={symbol} onChange={e=>setSymbol(e.target.value)}>{ASSETS.map(x=><option key={x}>{x}</option>)}</select><button onClick={onClose}>CLOSE</button></div></div>
  <div className="ofStatus"><b>{symbol}</b><span>{status}</span><span>Gamma {gammaTicker?`via ${gammaTicker}`:'NO OPTIONS PROXY'}</span></div>
  <div className="ofGrid"><section className="ofPanel chart"><h3>FULL MARKET CHART</h3><div className="ofChart"><TradingViewChart symbol={symbol} interval="1"/></div></section><section className="ofPanel"><h3>LIVE ORDERFLOW</h3>{exchangeSym?<><div className="ofMetrics"><div><span>Best bid</span><b>{n(bestBid,2)}</b></div><div><span>Best ask</span><b>{n(bestAsk,2)}</b></div><div><span>Spread</span><b>{n(spread,4)}</b></div><div><span>Trade delta</span><b>{n(delta,4)}</b></div></div><Spark trades={trades}/><div className="flowTape">{trades.slice(-18).reverse().map((t,i)=><div className={t.m?'sell':'buy'} key={i}><span>{t.m?'SELL':'BUY'}</span><b>{n(t.p,2)}</b><em>{n(t.q,5)}</em></div>)}</div></>:<div className="ofEmpty">No honest centralized order book exists for this instrument in the current free stack. Chart and gamma/proxy remain available.</div>}</section><section className="ofPanel"><h3>ORDER BOOK HEATMAP</h3>{exchangeSym?<Heatmap bids={book.bids} asks={book.asks}/>:<div className="ofEmpty">Heatmap disabled instead of fabricating liquidity. BTC/ETH use Binance public depth at 100 ms.</div>}</section><section className="ofPanel gamma"><h3>GAMMA EXPOSURE</h3>{gammaErr?<div className="ofEmpty">Gamma provider error: {gammaErr}</div>:gamma?<><div className="ofMetrics"><div><span>Underlying</span><b>{gamma.ticker||gammaTicker}</b></div><div><span>Spot</span><b>{n(gamma.spot,2)}</b></div><div><span>Regime</span><b>{gamma.regime||gamma.gammaRegime||'—'}</b></div><div><span>Zero gamma</span><b>{n(gamma.zeroGamma??gamma.zero_gamma??gamma.gammaFlip,2)}</b></div><div><span>Call wall</span><b>{n(gamma.callWall??gamma.call_wall,2)}</b></div><div><span>Put wall</span><b>{n(gamma.putWall??gamma.put_wall,2)}</b></div></div><GammaChart data={gamma}/><p className="ofNote">For indices/metals this is an explicitly labelled liquid options proxy, e.g. XAUUSD→GLD, NAS100→QQQ, SPX500→SPY.</p></>:<div className="ofEmpty">{gammaTicker?'Loading free gamma feed…':'No liquid US options proxy configured for this symbol.'}</div>}</section></div>
  <footer>Sources: Binance public market-data WebSocket for crypto order book/trades; AlgoXFlow public gamma endpoint for supported US options tickers/proxies. Orderflow is unavailable rather than invented for decentralized OTC FX/metals.</footer>
 </div></div>
}
