import React,{useEffect,useState}from'react';
import{BarChart3,Brain,Building2,CalendarDays,Database,FileText,Globe2,KeyRound,Landmark,MessageSquare,Newspaper,RefreshCw,Search,Ship,TrendingUp}from'lucide-react';
import TradingViewChart from'./TradingViewChart';
import ShippingMap from'./ShippingMap';
import EconomicCalendar from'./EconomicCalendar';
import NewsPanel from'./NewsPanel';
import ReportButton from'./ReportButton';
import GeopoliticalDesk from'./GeopoliticalDesk';

const API=import.meta.env.VITE_API_URL||'';
const US=['AAPL','MSFT','NVDA','AMZN','GOOGL','META','TSLA','AVGO','JPM','V','MA','LLY','WMT','XOM','COST','NFLX','AMD','CRM','ORCL','PLTR'];
const ID=['BBCA','BBRI','BMRI','BBNI','TLKM','ASII','AMMN','DSSA','BYAN','GOTO','ADRO','ANTM','INCO','MDKA','ICBP','INDF','UNVR','KLBF','PGAS','CPIN'];
const INDICES=['SPX','NDX','DJI','RUT','IHSG','LQ45'];
const FX=['XAUUSD','EURUSD','GBPUSD','USDJPY','BTCUSD','NAS100','US30'];
const TFS=['1m','5m','15m','1h','4h','1D'];
const tfMap={'1m':'1','5m':'5','15m':'15','1h':'60','4h':'240','1D':'D'};
const tabs=[['quant','Quant Markets',BarChart3],['indices','Global Indices',Landmark],['us','US Stocks',Building2],['idx','Indonesia Stocks',Building2],['screener','AI Stock Screener',Brain],['fundamentals','Fundamentals',Database],['macro','Macro / Intermarket',TrendingUp],['geo','Geopolitics',Globe2],['shipping','Shipping Map',Ship],['news','Live News',Newspaper],['events','Economic Events',CalendarDays],['luna','Luna AI',MessageSquare],['report','Report Engine',FileText]];
const fmt=(v,d=2)=>v==null||v===''||Number.isNaN(Number(v))?'—':Number(v).toLocaleString(undefined,{maximumFractionDigits:d});
const credsLoad=()=>{try{return JSON.parse(localStorage.getItem('night_quant_creds')||'{}')}catch{return{}}};
function Card({title,children,wide=false}){return <section className={`pCard ${wide?'wide':''}`}><h3>{title}</h3>{children}</section>}
function KV({k,v,tag}){return <div className="pKV"><span>{k}</span><b>{v}</b>{tag&&<i>{tag}</i>}</div>}
function fact(sec,key){const x=sec?.facts?.[key];return x?<>{fmt(x.value,2)} <small>{x.unit}</small></>:'—'}
function DirectionMatrix({mtf}){return <Card title="MULTI-TIMEFRAME DIRECTION"><div className="tfMatrix">{TFS.map(tf=>{const r=mtf?.timeframes?.[tf]||{};const a=r.action||'NO DATA';return <div key={tf} className={`tfRow ${a.toLowerCase().replace(' ','-')}`}><b>{tf}</b><strong>{a}</strong><span>P↑ {fmt(r.probability_up,1)}%</span><span>Ready {fmt(r.trade_readiness,0)}%</span></div>})}</div>{mtf?.valid&&<div className="tfConsensus"><b>CONSENSUS {mtf.action}</b><span>P↑ {fmt(mtf.probability_up,1)}%</span><span>Agreement {fmt(mtf.agreement,1)}%</span></div>}</Card>}

export default function ProductionApp(){
 const[tab,setTab]=useState('quant'),[symbol,setSymbol]=useState('XAUUSD'),[tf,setTf]=useState('5m'),[equity,setEquity]=useState(null),[equityMtf,setEquityMtf]=useState({}),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const[creds,setCreds]=useState(credsLoad),[keys,setKeys]=useState(false),[news,setNews]=useState({articles:[]}),[activity,setActivity]=useState({oil:{},shipping:{vessels:[]}}),[analysis,setAnalysis]=useState({}),[mtf,setMtf]=useState({});
 const[lunaMsg,setLunaMsg]=useState(''),[luna,setLuna]=useState([{role:'bot',text:'Luna AI online. Ask me about markets, stocks, macro, fundamentals, geopolitics, shipping, news, or the current terminal state.'}]),[lunaBusy,setLunaBusy]=useState(false);
 const[screenRegion,setScreenRegion]=useState('US'),[screenQ,setScreenQ]=useState('');
 async function post(path,body){const r=await fetch(API+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.detail||`API ${r.status}`);return j}
 async function get(path){const r=await fetch(API+path);const j=await r.json();if(!r.ok)throw new Error(j.detail||`API ${r.status}`);return j}
 async function loadEquity(s=symbol){setLoading(true);setError('');try{const[e,m]=await Promise.all([post('/api/equity',{symbol:s,credentials:creds}),post('/api/equity-mtf',{symbol:s,credentials:creds})]);setEquity(e);setEquityMtf(m)}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function loadQuant(){setLoading(true);setError('');try{const body={symbol,timeframe:tf,credentials:creds};const[a,m]=await Promise.all([post('/api/analyse',body),post('/api/analyse-mtf',body)]);setAnalysis(a);setMtf(m)}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function refreshIntel(){try{const[n,a]=await Promise.all([get(`/api/news/${symbol}`),get('/api/activity')]);setNews(n);setActivity(a)}catch{}}
 useEffect(()=>{refreshIntel();const t=setInterval(refreshIntel,30000);return()=>clearInterval(t)},[symbol]);
 useEffect(()=>{if(['us','idx','fundamentals','indices','screener'].includes(tab))loadEquity(symbol);else if(tab==='quant')loadQuant()},[symbol,tf]);
 function pickStock(s,desk){setSymbol(s);setTab(desk);setTimeout(()=>loadEquity(s),0)}
 function saveKeys(){localStorage.setItem('night_quant_creds',JSON.stringify(creds));setKeys(false);if(['us','idx','fundamentals','indices','screener'].includes(tab))loadEquity();else loadQuant()}
 async function askLuna(){const q=lunaMsg.trim();if(!q||lunaBusy)return;setLuna(x=>[...x,{role:'me',text:q}]);setLunaMsg('');setLunaBusy(true);try{const context={symbol,tab,timeframe:tf,equity,equityMtf,analysis,mtf,news,activity};const j=await post('/api/luna',{message:q,context,credentials:creds});setLuna(x=>[...x,{role:'bot',text:j.answer||'No response'}])}catch(e){setLuna(x=>[...x,{role:'bot',text:'Luna error: '+e.message}])}finally{setLunaBusy(false)}}
 const price=equity?.price,q=equity?.quote||{},sec=equity?.sec||{},td=equity?.fundamentals||{};
 const selectedList=screenRegion==='US'?US:ID,filtered=selectedList.filter(x=>x.includes(screenQ.toUpperCase()));

 const quant=<><div className="pHero"><Card title="FINAL QUANT BIAS"><strong>{analysis.bias||'—'}</strong><p>Action {analysis.action||'NO DATA'}</p></Card><Card title="DIRECTION"><strong>{fmt(analysis.probability_up,1)}%</strong><p>Upside probability</p></Card><Card title="EXPECTED VALUE"><strong>{fmt(analysis.ev_long_r,3)}R</strong><p>Long model expectancy</p></Card><Card title="READINESS"><strong>{fmt(analysis.trade_readiness,1)}%</strong><p>{analysis.regime||'—'} regime</p></Card></div><div className="quantSplit"><Card title="LIVE MARKET CHART" wide><div className="prodChart"><TradingViewChart symbol={symbol} interval={tfMap[tf]}/></div></Card><DirectionMatrix mtf={mtf}/></div></>;
 const equityDesk=<><div className="eqTop"><Card title="LATEST PRICE"><strong>{fmt(price,5)}</strong><p>{equity?.price_source||'NO SOURCE'}</p><span className={`fresh ${String(equity?.freshness).includes('LIVE')?'live':''}`}>{equity?.freshness||'NO DATA'}</span></Card><Card title="MARKET"><KV k="Market cap" v={fmt(q.marketCap,0)}/><KV k="Volume" v={fmt(q.regularMarketVolume,0)}/><KV k="Day change" v={q.regularMarketChangePercent==null?'—':fmt(q.regularMarketChangePercent,2)+'%'}/></Card><Card title="VALUATION"><KV k="Trailing P/E" v={fmt(q.trailingPE,2)}/><KV k="Forward P/E" v={fmt(q.forwardPE,2)}/><KV k="EPS TTM" v={fmt(q.epsTrailingTwelveMonths,3)}/></Card><Card title="DATA STATUS"><KV k="Price" v={equity?.freshness||'NO DATA'}/><KV k="Fundamental" v={sec.available?'LATEST REPORTED':'PROVIDER DEPENDENT'}/><KV k="Twelve fundamentals" v={td.available?'CONNECTED':'NO ENTITLEMENT / KEY'}/></Card></div><div className="eqLayout"><Card title={`${symbol} MARKET CHART`} wide><div className="prodChart"><TradingViewChart symbol={symbol} interval="5"/></div></Card><DirectionMatrix mtf={equityMtf}/><Card title="LATEST REPORTED FUNDAMENTALS"><KV k="Revenue" v={fact(sec,'revenue')}/><KV k="Net income" v={fact(sec,'net_income')}/><KV k="Operating income" v={fact(sec,'operating_income')}/><KV k="Assets" v={fact(sec,'assets')}/><KV k="Liabilities" v={fact(sec,'liabilities')}/><KV k="Equity" v={fact(sec,'equity')}/><KV k="Operating cash flow" v={fact(sec,'operating_cash_flow')}/><KV k="Diluted EPS" v={fact(sec,'eps_diluted')}/><p className="sourceNote">US filing source: {sec.source||'—'}. IDX fundamentals use Twelve Data when the plan permits it.</p></Card></div></>;
 const indices=<><div className="tickerGrid">{INDICES.map(s=><button key={s} className={symbol===s?'on':''} onClick={()=>pickStock(s,'indices')}>{s}</button>)}</div>{equityDesk}</>;
 const us=<><div className="tickerGrid">{US.map(s=><button key={s} className={symbol===s?'on':''} onClick={()=>pickStock(s,'us')}>{s}</button>)}</div>{equityDesk}</>;
 const idx=<><div className="tickerGrid">{ID.map(s=><button key={s} className={symbol===s?'on':''} onClick={()=>pickStock(s,'idx')}>{s}</button>)}</div>{equityDesk}</>;
 const fundamentals=<><div className="fundMind"><div className="root">{symbol}</div><div className="nodes"><span>VALUATION<b>{fmt(q.trailingPE,2)} P/E</b></span><span>GROWTH<b>Latest filings</b></span><span>QUALITY<b>{sec.available?'SEC VERIFIED':'PROVIDER DATA'}</b></span><span>LIQUIDITY<b>{fmt(q.regularMarketVolume,0)} volume</b></span><span>MACRO<b>Rates · FX · inflation</b></span><span>NEWS<b>{news.count||0} headlines</b></span><span>GEOPOLITICS<b>Supply-chain exposure</b></span><span>QUANT<b>{equityMtf?.action||'Run quant'}</b></span></div></div>{equityDesk}</>;
 const screener=<><div className="screenBar"><button className={screenRegion==='US'?'on':''} onClick={()=>setScreenRegion('US')}>US</button><button className={screenRegion==='ID'?'on':''} onClick={()=>setScreenRegion('ID')}>INDONESIA</button><div><Search size={14}/><input value={screenQ} onChange={e=>setScreenQ(e.target.value)} placeholder="Search ticker"/></div></div><div className="screenGrid">{filtered.map(s=><button key={s} onClick={()=>pickStock(s,screenRegion==='US'?'us':'idx')}><b>{s}</b><span>Open full institutional analysis</span><i>LIVE DATA ON SELECT</i></button>)}</div></>;
 const macro=<div className="pGrid"><Card title="ENERGY">{Object.entries(activity.oil||{}).map(([k,v])=><KV key={k} k={k} v={v?.price==null?'—':fmt(v.price,2)+' '+(v.currency||'')}/>)}</Card><Card title="QUANT MACRO STATE"><KV k="Macro source" v={analysis.macro_source||'FRED key required'}/><KV k="Intermarket" v={fmt(analysis.components?.intermarket,3)}/><KV k="Macro factor" v={fmt(analysis.components?.macro,3)}/></Card><Card title="EVENT RISK"><KV k="Current" v={fmt(analysis.event_risk,0)+'%'}/><KV k="News headlines" v={news.count||0}/></Card></div>;
 const geo=<GeopoliticalDesk news={news} shipping={activity.shipping||{}}/>;
 const shipping=<Card title="LIVE MARITIME MAP" wide><ShippingMap shipping={activity.shipping||{}}/></Card>;
 const newsView=<Card title="24/7 MARKET NEWS" wide><NewsPanel news={news}/></Card>;
 const events=<Card title="ECONOMIC CALENDAR" wide><EconomicCalendar/></Card>;
 const lunaView=<div className="lunaDesk"><div className="lunaHead"><Brain/><div><h2>Luna AI</h2><p>AI market intelligence using your free Gemini/OpenRouter key + NIGHT terminal context.</p></div></div><div className="lunaLog">{luna.map((x,i)=><div key={i} className={`lunaBubble ${x.role}`}>{x.text}</div>)}</div><div className="lunaInput"><input value={lunaMsg} onChange={e=>setLunaMsg(e.target.value)} onKeyDown={e=>e.key==='Enter'&&askLuna()} placeholder="Ask Luna anything about the market..."/><button onClick={askLuna} disabled={lunaBusy}>{lunaBusy?'THINKING…':'ASK LUNA'}</button></div></div>;
 const report=<Card title="INSTITUTIONAL REPORT ENGINE"><p>Generate the current NIGHT snapshot on demand.</p><ReportButton symbol={symbol} timeframe={tf} data={analysis} mtf={mtf} news={news}/></Card>;
 const views={quant,indices,us,idx,screener,fundamentals,macro,geo,shipping,news:newsView,events,luna:lunaView,report};

 return <div className="prodApp"><aside><div className="prodLogo"><Brain/><b>NIGHT</b><small>INSTITUTION</small></div>{tabs.map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={16}/><span>{label}</span></button>)}</aside><main><header><div><small>NIGHT INSTITUTIONAL MARKET INTELLIGENCE</small><h1>{symbol} <span>{tab.toUpperCase()}</span></h1></div><div className="headActions"><button onClick={()=>setKeys(v=>!v)}><KeyRound size={14}/> DATA KEYS</button><i>● SYSTEM LIVE</i></div></header><div className="prodToolbar"><select value={symbol} onChange={e=>setSymbol(e.target.value)}>{[...FX,...INDICES,...US,...ID].map(x=><option key={x}>{x}</option>)}</select><select value={tf} onChange={e=>setTf(e.target.value)}>{TFS.map(x=><option key={x}>{x}</option>)}</select><button onClick={()=>['us','idx','indices','fundamentals','screener'].includes(tab)?loadEquity():loadQuant()}><RefreshCw size={14}/>{loading?' LOADING':' REFRESH DATA'}</button></div>{keys&&<div className="prodKeys"><h3>API KEYS — STORED LOCALLY IN THIS BROWSER</h3><input type="password" placeholder="Gemini API key (Luna AI primary)" value={creds.gemini_key||''} onChange={e=>setCreds({...creds,gemini_key:e.target.value})}/><input type="password" placeholder="OpenRouter API key (Luna AI fallback)" value={creds.openrouter_key||''} onChange={e=>setCreds({...creds,openrouter_key:e.target.value})}/><input type="password" placeholder="Twelve Data API key" value={creds.twelve_key||''} onChange={e=>setCreds({...creds,twelve_key:e.target.value})}/><input type="password" placeholder="FRED API key" value={creds.fred_key||''} onChange={e=>setCreds({...creds,fred_key:e.target.value})}/><button onClick={saveKeys}>SAVE LOCALLY + REFRESH</button><p>Keys are saved to localStorage on this device and sent only when the relevant NIGHT API request needs them. Do not use this on a shared/public computer.</p></div>}{error&&<div className="prodError">{error}</div>}<div className="prodContent">{views[tab]||quant}</div><footer>Price freshness is shown explicitly. Fundamentals are latest reported filings/data, not tick data. NIGHT never substitutes stale or cross-instrument prices as live.</footer></main></div>
}
