import React,{useEffect,useMemo,useState}from'react';
import{createPortal}from'react-dom';
import{RefreshCw}from'lucide-react';
import OrderflowDesk from'./OrderflowDesk';

const API=import.meta.env.VITE_API_URL||'';
const FX_UNIVERSE=['XAUUSD','XAGUSD','EURUSD','GBPUSD','USDJPY','USDCHF','USDCAD','AUDUSD','NZDUSD','EURGBP','EURJPY','EURCHF','EURCAD','EURAUD','EURNZD','GBPJPY','GBPCHF','GBPCAD','GBPAUD','GBPNZD','AUDJPY','AUDCHF','AUDCAD','AUDNZD','NZDJPY','NZDCHF','NZDCAD','CADJPY','CADCHF','CHFJPY','BTCUSD','ETHUSD','NAS100','US30','SPX500'];
const NEWS_ASSETS=['XAUUSD','EURUSD','GBPUSD','USDJPY','AUDUSD','USDCAD','USDCHF','NAS100','SPX500','US30','BTCUSD'];
const EVENTS=['NFP','UNEMPLOYMENT','ADP','CLAIMS','JOLTS','CPI','CORE CPI','PPI','PCE','CORE PCE','RETAIL SALES','GDP','DURABLE GOODS','HOUSING STARTS','CONSUMER SENTIMENT','INDUSTRIAL PRODUCTION','FOMC'];
const credsLoad=()=>{try{return JSON.parse(localStorage.getItem('night_quant_creds')||'{}')}catch{return{}}};
const fmt=(v,d=1)=>v==null||Number.isNaN(Number(v))?'—':Number(v).toFixed(d);

function compactContext(c={}){
 const n=c.news||{},a=c.activity||{},s=a.shipping||{};
 return {symbol:c.symbol,market:c.market,tab:c.tab,timeframe:c.timeframe,
  analysis:c.analysis?{action:c.analysis.action,bias:c.analysis.bias,probability_up:c.analysis.probability_up,trade_readiness:c.analysis.trade_readiness,regime:c.analysis.regime,macro_source:c.analysis.macro_source,macro_details:c.analysis.macro_details,institutional_factors:c.analysis.institutional_factors,event_risk:c.analysis.event_risk}:null,
  mtf:c.mtf?{action:c.mtf.action,probability_up:c.mtf.probability_up,agreement:c.mtf.agreement,average_readiness:c.mtf.average_readiness,timeframes:c.mtf.timeframes}:null,
  equity:c.equity?{symbol:c.equity.symbol,price:c.equity.price,freshness:c.equity.freshness,signal:c.equity.signal,quote:c.equity.quote,sec:c.equity.sec,shipping_exposure:c.equity.shipping_exposure}:null,
  equityMtf:c.equityMtf?{action:c.equityMtf.action,probability_up:c.equityMtf.probability_up,agreement:c.equityMtf.agreement,timeframes:c.equityMtf.timeframes}:null,
  ranked:(c.ranked||[]).slice(0,5).map(x=>({symbol:x.symbol,action:x.action,score:x.score,agreement:x.agreement,probability_up:x.probability_up,average_readiness:x.average_readiness})),
  news:{source:n.source,score:n.score,count:n.count,articles:(n.articles||[]).slice(0,10)},
  activity:{oil:a.oil,shipping:{count:s.count,analytics:s.analytics},news_count:a.news_count,event_risk:a.event_risk}}
}

async function api(path,opts){const r=await fetch(API+path,opts);const text=await r.text();let j;try{j=text?JSON.parse(text):{}}catch{j={detail:text||`HTTP ${r.status}`}}if(!r.ok)throw new Error(j.detail||j.error||`API ${r.status}`);return j}
async function post(path,body){return api(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})}
async function get(path){return api(path)}

export default function TerminalEnhancements(){
 const[mode,setMode]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[rows,setRows]=useState([]),[ai,setAi]=useState(''),[event,setEvent]=useState('NFP'),[eventData,setEventData]=useState(null);
 const creds=useMemo(credsLoad,[mode]);
 useEffect(()=>{
  const nativeFetch=window.fetch.bind(window);
  window.fetch=async(input,init={})=>{let nextInit=init;const url=typeof input==='string'?input:(input?.url||'');if(url.includes('/api/luna')&&init?.body){try{const b=JSON.parse(init.body);if(b.context)b.context=compactContext(b.context);nextInit={...init,body:JSON.stringify(b)}}catch{}}const r=await nativeFetch(input,nextInit);const ct=r.headers.get('content-type')||'';if(url.includes('/api/')&&!ct.includes('application/json')){const text=await r.clone().text();return new Response(JSON.stringify({detail:text||`HTTP ${r.status}`}),{status:r.status,headers:{'Content-Type':'application/json'}})}return r};
  let raf=0;
  const apply=()=>{
   raf=0;
   const sel=document.querySelector('.prodToolbar select');if(sel){const have=new Set([...sel.options].map(o=>o.value));FX_UNIVERSE.forEach(s=>{if(!have.has(s)){const o=document.createElement('option');o.value=s;o.textContent=s;sel.appendChild(o)}})}
   const app=document.querySelector('.prodApp'),aside=app?.querySelector('aside'),logo=aside?.querySelector('.prodLogo');
   if(app&&localStorage.getItem('night_sidebar_collapsed')==='1')app.classList.add('sideCollapsed');
   if(aside&&!aside.querySelector('[data-sidebar-toggle]')){const b=document.createElement('button');b.dataset.sidebarToggle='1';b.className='sidebarToggle sideNavToggle';b.innerHTML='<span class="sideToggleIcon">☰</span><span class="sideToggleLabel">Collapse sidebar</span>';b.title='Open / close sidebar';b.onclick=()=>{const collapsed=app?.classList.toggle('sideCollapsed');localStorage.setItem('night_sidebar_collapsed',collapsed?'1':'0');b.querySelector('.sideToggleLabel').textContent=collapsed?'Expand sidebar':'Collapse sidebar'};(logo?logo.after(b):aside.prepend(b))}
   const toggle=aside?.querySelector('[data-sidebar-toggle] .sideToggleLabel');if(toggle)toggle.textContent=app?.classList.contains('sideCollapsed')?'Expand sidebar':'Collapse sidebar';
   if(aside&&!aside.querySelector('[data-orderflow-desk]')){const b=document.createElement('button');b.dataset.orderflowDesk='1';b.innerHTML='<span style="font-size:16px">≋</span><span>Orderflow / Gamma</span>';b.onclick=()=>setMode('orderflow');aside.appendChild(b)}
   if(aside&&!aside.querySelector('[data-news-prediction]')){const b=document.createElement('button');b.dataset.newsPrediction='1';b.innerHTML='<span style="font-size:16px">◈</span><span>News Prediction</span>';b.onclick=()=>setMode('market');aside.appendChild(b)}
   if(aside&&!aside.querySelector('[data-news-event-analysis]')){const b=document.createElement('button');b.dataset.newsEventAnalysis='1';b.innerHTML='<span style="font-size:16px">◇</span><span>News Prediction Analysis</span>';b.onclick=()=>setMode('event');aside.appendChild(b)}
   const gem=document.querySelector('.prodKeys input[placeholder*="Gemini"]');if(gem&&gem.style.display!=='none')gem.style.display='none';
   const lunaCopy='AI market intelligence using OpenRouter + compact NIGHT terminal context.';document.querySelectorAll('.lunaHead p').forEach(p=>{if(p.textContent!==lunaCopy)p.textContent=lunaCopy});
  };
  const scheduleApply=()=>{if(!raf)raf=requestAnimationFrame(apply)};
  apply();const mo=new MutationObserver(scheduleApply);mo.observe(document.body,{childList:true,subtree:true});return()=>{mo.disconnect();if(raf)cancelAnimationFrame(raf);window.fetch=nativeFetch}
 },[]);
 async function runMarket(){setBusy(true);setError('');setAi('');try{const baseNews=await Promise.all(NEWS_ASSETS.map(async s=>{try{return[s,await get(`/api/news/${s}`)]}catch{return[s,{articles:[],count:0}]}}));const mtfs=await Promise.all(NEWS_ASSETS.map(async s=>{try{return[s,await post('/api/analyse-mtf',{symbol:s,timeframe:'15m',credentials:creds})]}catch{return[s,{valid:false}]}}));const newsMap=Object.fromEntries(baseNews),mtfMap=Object.fromEntries(mtfs);const built=NEWS_ASSETS.map(s=>{const n=newsMap[s]||{},m=mtfMap[s]||{},score=Number(n.score||0),p=Number(m.probability_up||50);let newsDir=score>.08?'BULLISH':score<-.08?'BEARISH':'NEUTRAL';let tech=m.action==='LONG'?'BULLISH':m.action==='SHORT'?'BEARISH':'NEUTRAL';let aligned=newsDir==='NEUTRAL'||tech==='NEUTRAL'||newsDir===tech;let evidence=Math.min(95,25+(n.count||0)*2+Math.abs(score)*35);let model=Math.min(95,Math.abs(p-50)*1.3+Number(m.agreement||0)*.45+Number(m.average_readiness||0)*.25);let confidence=Math.round(evidence*.45+model*.55);let direction=newsDir==='NEUTRAL'?tech:aligned?newsDir:'MIXED';return{symbol:s,direction,newsDir,tech,confidence,evidence,headlines:(n.articles||[]).slice(0,4),p,agreement:m.agreement||0,readiness:m.average_readiness||0,source:n.source||'—'}});setRows(built.sort((a,b)=>b.confidence-a.confidence));if(creds.openrouter_key){const context={assets:built.slice(0,7),headlines:Object.fromEntries(NEWS_ASSETS.map(s=>[s,(newsMap[s]?.articles||[]).slice(0,4)]))};const j=await post('/api/luna',{message:'Analyze the current released news in this context. Rank the strongest asset impacts, explain transmission through USD/yields/risk, conflicting evidence, invalidation, and distinguish actual released information from expectations. Include a confidence percentage for each conclusion; call it evidence confidence, not certainty.',context,credentials:creds});setAi(j.answer||'No AI response')}}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function runEvent(){setBusy(true);setError('');setAi('');try{const d=await post('/api/news-prediction',{event,credentials:creds});setEventData(d);if(!d.ok){setError(d.error||'Prediction data unavailable');return}if(creds.openrouter_key){const context={event:d.event,label:d.label,stance:d.stance,hawkish_pct:d.hawkish_pct,dovish_pct:d.dovish_pct,neutral_pct:d.neutral_pct,evidence_confidence_pct:d.evidence_confidence_pct,target:d.target,evidence:(d.evidence||[]).slice(0,8),proof:d.news_proof};const q=`This is a PRE-RELEASE scenario analysis for ${event}; the target release has NOT happened yet. Explain why the currently released leading indicators imply the supplied hawkish/dovish/neutral probabilities. Discuss the strongest evidence, conflicting indicators, what would invalidate the lean, and likely USD/XAUUSD/yields/equity reaction IF the predicted scenario occurs. Never state the future result as certain.`;const j=await post('/api/luna',{message:q,context,credentials:creds});setAi(j.answer||'No AI response')}}catch(e){setError(e.message)}finally{setBusy(false)}}
 useEffect(()=>{if(mode==='market'&&!rows.length)runMarket();if(mode==='event'&&!eventData)runEvent()},[mode]);
 if(!mode)return null;const close=()=>setMode(null);
 if(mode==='orderflow')return createPortal(<OrderflowDesk onClose={close}/>,document.body);
 if(mode==='event')return createPortal(<div className="newsPredictionOverlay"><div className="newsPredShell"><div className="newsPredHead"><div><small>NIGHT PRE-RELEASE MACRO INTELLIGENCE</small><h1>NEWS PREDICTION ANALYSIS</h1><p>Before the release: latest leading indicators + historical relationships → Hawkish / Dovish / Neutral scenario probabilities.</p></div><div><select className="eventSelect" value={event} onChange={e=>{setEvent(e.target.value);setEventData(null);setAi('')}}>{EVENTS.map(x=><option key={x}>{x}</option>)}</select><button onClick={runEvent}><RefreshCw size={14}/>{busy?' MODELING…':' PREDICT'}</button><button onClick={close}>CLOSE</button></div></div>{error&&<div className="prodError">{error}</div>}{eventData?.ok&&<><div className="predictionStance"><span>PRE-RELEASE LEAN</span><strong>{eventData.stance}</strong><small>{eventData.label} · confidence in evidence {fmt(eventData.evidence_confidence_pct)}%</small></div><div className="policyMeter"><div><span>HAWKISH</span><b>{fmt(eventData.hawkish_pct)}%</b><i><em style={{width:`${eventData.hawkish_pct}%`}}/></i></div><div><span>DOVISH</span><b>{fmt(eventData.dovish_pct)}%</b><i><em style={{width:`${eventData.dovish_pct}%`}}/></i></div><div><span>NEUTRAL</span><b>{fmt(eventData.neutral_pct)}%</b><i><em style={{width:`${eventData.neutral_pct}%`}}/></i></div><div><span>EVIDENCE CONFIDENCE</span><b>{fmt(eventData.evidence_confidence_pct)}%</b><i><em style={{width:`${eventData.evidence_confidence_pct}%`}}/></i></div></div><section className="newsAiBrief"><h3>MACRO PROOF · ALREADY RELEASED DATA</h3><p className="predictionExplain">{eventData.explanation}</p><div className="macroEvidenceGrid">{(eventData.evidence||[]).map((x,i)=><article key={`${x.series_id}-${i}`} className={`macroEvidence ${String(x.signal).toLowerCase()}`}><header><b>{x.name}</b><strong>{x.signal}</strong></header><div><span>Latest</span><b>{fmt(x.latest,4)}</b><small>{x.latest_date}</small></div><div><span>Previous</span><b>{fmt(x.previous,4)}</b><small>{x.previous_date}</small></div><div><span>Change</span><b>{Number(x.change)>=0?'+':''}{fmt(x.change,4)}</b><small>{x.policy_effect}</small></div><div><span>Past relationship</span><b>{fmt(x.historical_correlation,2)}</b><small>historical directional correlation</small></div></article>)}</div></section><section className="newsAiBrief"><h3>PROOF SUMMARY</h3><div className="headlineStack">{(eventData.news_proof||[]).map((p,i)=><article key={i}><b>{p}</b></article>)}</div></section></>}<section className="newsAiBrief"><h3>LUNA / OPENROUTER — PRE-RELEASE EXPLANATION</h3><pre>{ai||(creds.openrouter_key?'Run prediction for AI explanation.':'Add OpenRouter key for AI narrative. Quant probabilities and macro proof use FRED and work without Luna.')}</pre></section></div></div>,document.body);
 return createPortal(<div className="newsPredictionOverlay"><div className="newsPredShell"><div className="newsPredHead"><div><small>NIGHT INTELLIGENCE</small><h1>NEWS PREDICTION</h1><p>Live headlines + current MTF technical state. Confidence is evidence strength, not guaranteed accuracy.</p></div><div><button onClick={runMarket}><RefreshCw size={14}/>{busy?' ANALYZING…':' REFRESH'}</button><button onClick={close}>CLOSE</button></div></div>{error&&<div className="prodError">{error}</div>}<div className="newsPredGrid">{rows.map((r,i)=><section key={r.symbol} className="newsPredCard"><div className="newsPredRank">#{i+1} NEWS OPPORTUNITY <b>{r.direction}</b></div><h2>{r.symbol}<strong>{r.confidence}%</strong></h2><div className="decisionGrid"><div><span>NEWS BIAS</span><b>{r.newsDir}</b></div><div><span>TECH MTF</span><b>{r.tech}</b></div><div><span>P↑</span><b>{fmt(r.p)}%</b></div><div><span>AGREEMENT</span><b>{fmt(r.agreement)}%</b></div><div><span>READINESS</span><b>{fmt(r.readiness)}%</b></div><div><span>EVIDENCE CONF.</span><b>{fmt(r.evidence)}%</b></div></div><div className="headlineStack">{r.headlines.map((h,j)=><article key={j}><b>{h.title||'Untitled headline'}</b><span>{h.domain||''} · {r.source}</span></article>)}</div></section>)}</div><section className="newsAiBrief"><h3>OPENROUTER AI — RELEASED NEWS TRANSMISSION BRIEF</h3><pre>{ai||(creds.openrouter_key?'Generating…':'Add OpenRouter key for AI narrative.')}</pre></section></div></div>,document.body)
}
